# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-o1Y1O-YaB2GNVaXpKuqY9MIe-anJOk
"""

# -*- coding: utf-8 -*-
"""
Mental Health Filter dan Preprocessor untuk Google Colab
=========================================================

File: mental_health_filter_colab.py
Versi: 1.0
Terakhir diupdate: 2025-11-30
Penulis: MentalTrendAI Team
Lisensi: MIT

DESKRIPSI:
    Script gabungan yang menggabungkan:
    1. mental_health_filter.py - Filter dan labeling konten kesehatan mental
    2. preprocess_ppkm_for_mental_health.py - Preprocessor untuk dataset PPKM

    Didesain untuk dijalankan di Google Colab dengan upload file manual.

ARSITEKTUR FILTERING:
    ┌─────────────────────────────────────────────────────────────────┐
    │                    Mental Health Filter                          │
    ├─────────────────────────────────────────────────────────────────┤
    │                                                                  │
    │  ┌──────────────┐    ┌──────────────┐    ┌──────────────┐      │
    │  │   Tweet      │───▶│   Keyword    │───▶│  Contextual  │      │
    │  │   Input      │    │   Matching   │    │   Analysis   │      │
    │  └──────────────┘    └──────────────┘    │   (BERT)     │      │
    │                             │            └──────────────┘      │
    │                             ▼                    │              │
    │                    ┌──────────────┐              │              │
    │                    │   Combine    │◀─────────────┘              │
    │                    │   Results    │                             │
    │                    └──────────────┘                             │
    │                             │                                   │
    │                             ▼                                   │
    │                    ┌──────────────┐                             │
    │                    │   Output:    │                             │
    │                    │  - Category  │                             │
    │                    │  - Confidence│                             │
    │                    │  - Keywords  │                             │
    │                    └──────────────┘                             │
    └─────────────────────────────────────────────────────────────────┘

FUNGSI UTAMA:
    1. Upload file dataset via files.upload() (Colab) atau file path (lokal)
    2. Filter konten berdasarkan kata kunci kesehatan mental (220+ keywords)
    3. Klasifikasi kontekstual menggunakan BERT embeddings (IndoBERT)
    4. Kategori mental health yang didukung:
       - depression (depresi)
       - anxiety (kecemasan)
       - stress (stres)
       - ptsd (Post-Traumatic Stress Disorder)
       - bipolar (gangguan bipolar)
       - schizophrenia (skizofrenia)
       - social_support (dukungan sosial)
       - therapy (terapi)
       - suicide (bunuh diri/self-harm)
       - general_mental_health (kesehatan mental umum)
    5. Support untuk bahasa Indonesia dan Inggris
    6. Konversi format untuk pipeline analysis

CARA MENGGUNAKAN DI GOOGLE COLAB:
    1. Jalankan semua cell
    2. Upload file dataset ketika diminta:
       - INA_TweetsPPKM_Raw.csv (required) - Data tweet mentah
       - INA_TweetsPPKM_Labeled_Pure.csv (optional) - Untuk sentiment labels
    3. Proses otomatis filter dan preprocessing
    4. Download hasil dari Colab:
       - INA_TweetsPPKM_MentalHealth_Filtered.csv
       - INA_TweetsPPKM_MentalHealth_Filtered_pipeline_ready.csv
       - mental_health_filter_report.json
       - preprocessing_report.json
       - sample_filtered_tweets.txt

CARA MENGGUNAKAN LOKAL:
    1. Letakkan file CSV di direktori yang sama dengan script
    2. Jalankan: python mental_health_filter_colab.py
    3. Hasil akan disimpan di folder 'data/'

OUTPUT FILES:
    - INA_TweetsPPKM_MentalHealth_Filtered.csv: Data yang sudah difilter
    - INA_TweetsPPKM_MentalHealth_Filtered_pipeline_ready.csv: Data siap pipeline
    - mental_health_filter_report.json: Statistik dan distribusi filtering
    - preprocessing_report.json: Laporan lengkap preprocessing
    - sample_filtered_tweets.txt: Sampel tweet untuk verifikasi manual

DEPENDENCIES:
    Required:
    - pandas: Manipulasi data
    - numpy: Operasi numerik

    Optional (untuk contextual analysis):
    - torch: PyTorch backend
    - transformers: Model BERT (IndoBERT)
    - sklearn: Cosine similarity calculation

STRUKTUR FILE:
    ┌─────────────────────────────────────────────────────────────────┐
    │  SECTION 1: Imports dan Dependencies                            │
    │  SECTION 1.5: Constants (MAX_KEYWORDS_TO_STORE, DEFAULT_SENTIMENT)│
    │  SECTION 2: Mental Health Keywords (10 kategori, 220+ keywords) │
    │  SECTION 3: MentalHealthFilter Class (keyword + BERT filtering) │
    │  SECTION 4: PPKMPreprocessor Class (format conversion)          │
    │  SECTION 5: File Upload Functions (Colab/Local)                 │
    │  SECTION 6: Main Execution                                       │
    │  SECTION 7: Demo Functions                                       │
    └─────────────────────────────────────────────────────────────────┘
"""

# =============================================================================
# SECTION 1: IMPORTS AND DEPENDENCIES
# =============================================================================
# Import semua library yang diperlukan untuk filtering dan preprocessing

import pandas as pd          # Manipulasi data tabular (DataFrame, read_csv)
import numpy as np           # Operasi numerik (array, reshape)
import re                    # Regular expressions untuk text cleaning
import json                  # Parsing dan writing JSON files
import os                    # Operasi filesystem (path, exists)
import io                    # Input/Output untuk file handling di Colab
from typing import List, Dict, Tuple  # Type hints untuk dokumentasi
from datetime import datetime         # Timestamp untuk laporan

# Cek apakah berjalan di Google Colab atau lokal
# Ini mempengaruhi cara upload/download file
try:
    import google.colab      # Module khusus Google Colab
    IN_COLAB = True          # Flag: berjalan di Colab
    print("✓ Running in Google Colab")
except ImportError:
    IN_COLAB = False         # Flag: berjalan di lokal
    print("✓ Running in local environment")

# Optional dependencies untuk BERT contextual analysis
# Jika tidak tersedia, akan fallback ke keyword-only mode
try:
    import torch                                   # PyTorch untuk tensor operations
    from transformers import AutoTokenizer, AutoModel  # Hugging Face Transformers
    BERT_AVAILABLE = True    # Flag: BERT tersedia
    print("✓ BERT dependencies tersedia (torch, transformers)")
except ImportError:
    BERT_AVAILABLE = False   # Flag: BERT tidak tersedia
    print("⚠ torch/transformers tidak tersedia. Menggunakan keyword-only mode.")
    print("  Install dengan: pip install torch transformers")

# Check sklearn untuk cosine_similarity calculation
# Jika tidak tersedia, akan menggunakan numpy manual implementation
SKLEARN_AVAILABLE = False
try:
    from sklearn.metrics.pairwise import cosine_similarity  # Similarity calculation
    SKLEARN_AVAILABLE = True  # Flag: sklearn tersedia
except ImportError:
    print("⚠ sklearn tidak tersedia. Menggunakan numpy untuk cosine similarity.")

# =============================================================================
# SECTION 1.5: CONSTANTS
# =============================================================================
# Konstanta global yang digunakan dalam filtering

# Maximum number of matched keywords to store in output
# Membatasi jumlah keyword yang disimpan untuk efisiensi storage
MAX_KEYWORDS_TO_STORE = 5

# Default sentiment value for unmatched tweets
# 0 = Netral (sesuai mapping dataset PPKM)
DEFAULT_SENTIMENT = 0

# =============================================================================
# SECTION 2: MENTAL HEALTH KEYWORDS
# =============================================================================
# Daftar kata kunci kesehatan mental dalam Bahasa Indonesia dan Inggris

def load_mental_health_keywords() -> Dict[str, List[str]]:
    """
    Load kata kunci kesehatan mental berdasarkan kategori.

    Fungsi ini mengembalikan dictionary yang berisi daftar kata kunci
    untuk setiap kategori kesehatan mental. Kata kunci mencakup:
    - Bahasa Indonesia (primer untuk dataset PPKM)
    - Bahasa Inggris (untuk kompatibilitas)

    Total: 220+ kata kunci dalam 10 kategori

    KATEGORI DAN CONTOH:
    ┌─────────────────────┬──────────────────────────────────────────┐
    │ Kategori            │ Contoh Keyword                           │
    ├─────────────────────┼──────────────────────────────────────────┤
    │ depression          │ depresi, sedih, murung, hopeless         │
    │ anxiety             │ cemas, khawatir, panik, nervous          │
    │ stress              │ stres, burnout, overwhelmed              │
    │ ptsd                │ trauma, flashback, mimpi buruk           │
    │ bipolar             │ mood swing, manik, euphoria              │
    │ schizophrenia       │ halusinasi, delusi, paranoid             │
    │ social_support      │ dukungan, curhat, support group          │
    │ therapy             │ terapi, konseling, psikolog              │
    │ suicide             │ bunuh diri, self harm (SENSITIF)         │
    │ general_mental_health│ kesehatan mental, mental health         │
    └─────────────────────┴──────────────────────────────────────────┘

    Returns:
        Dict[str, List[str]]: Dictionary dengan struktur:
            {
                'category_name': ['keyword1', 'keyword2', ...],
                ...
            }

    Note:
        Kata kunci dalam kategori 'suicide' adalah SENSITIF dan memerlukan
        penanganan khusus dalam analisis dan visualisasi.

    Example:
        >>> keywords = load_mental_health_keywords()
        >>> print(keywords['depression'][:3])
        ['depresi', 'sedih', 'murung']
    """
    # Dictionary kata kunci per kategori kesehatan mental
    # Setiap kategori memiliki keywords dalam Bahasa Indonesia dan Inggris
    keywords = {
        # ==== KATEGORI 1: DEPRESI ====
        # Gejala: perasaan sedih berkepanjangan, kehilangan minat, putus asa
        'depression': [
            # Bahasa Indonesia - Kata kunci umum depresi
            'depresi', 'sedih', 'murung', 'putus asa', 'tidak berharga',
            'tidak ada harapan', 'hampa', 'kosong', 'kehilangan minat',
            'tidak bahagia', 'sendu', 'galau berkepanjangan', 'down terus',
            'tertekan', 'terpuruk', 'kecewa hidup', 'lelah hidup',
            # Bahasa Inggris - English keywords
            'depression', 'depressed', 'hopeless', 'worthless', 'sad',
            'melancholy', 'despair', 'miserable', 'unhappy', 'gloomy',
            'empty feeling', 'no interest', 'cant enjoy', 'numb'
        ],

        # ==== KATEGORI 2: KECEMASAN ====
        # Gejala: khawatir berlebihan, panik, takut tanpa alasan jelas
        'anxiety': [
            # Bahasa Indonesia - Kata kunci kecemasan
            'cemas', 'khawatir', 'gelisah', 'panik', 'takut berlebihan',
            'overthinking', 'tidak tenang', 'was-was', 'parno', 'anxious',
            'anxiety', 'grogi', 'nervous', 'resah', 'deg-degan',
            'jantung berdebar', 'keringat dingin', 'sesak napas karena cemas',
            # Bahasa Inggris - English keywords
            'anxiety', 'anxious', 'worried', 'panic', 'fear',
            'nervous', 'restless', 'uneasy', 'apprehensive',
            'panic attack', 'social anxiety', 'generalized anxiety'
        ],

        # ==== KATEGORI 3: STRES ====
        # Gejala: kelelahan mental, burnout, tidak bisa mengatasi tekanan
        'stress': [
            # Bahasa Indonesia - Kata kunci stres
            'stress', 'stres', 'tertekan', 'beban', 'burnout',
            'kelelahan mental', 'mental breakdown', 'overwhelmed',
            'kewalahan', 'tidak kuat', 'cape mental', 'capek pikiran',
            'mental drop', 'jenuh', 'tekanan hidup', 'tekanan kerja',
            # Bahasa Inggris - English keywords
            'stress', 'stressed', 'stressed out', 'burn out', 'burnout',
            'overwhelmed', 'pressure', 'mental exhaustion', 'worn out',
            'breaking point', 'cant cope', 'too much pressure'
        ],

        # ==== KATEGORI 4: PTSD ====
        # Gejala: trauma, flashback, mimpi buruk berulang
        'ptsd': [
            # Bahasa Indonesia - Kata kunci PTSD
            'trauma', 'traumatis', 'kilas balik', 'mimpi buruk terus',
            'tidak bisa lupakan', 'tersiksa ingatan', 'ptsd',
            'post traumatic', 'flashback', 'teringat terus',
            # Bahasa Inggris - English keywords
            'ptsd', 'post traumatic', 'traumatic', 'flashback',
            'nightmares', 'haunted', 'cant forget', 'reliving'
        ],

        # ==== KATEGORI 5: BIPOLAR ====
        # Gejala: mood swing ekstrem, periode manik dan depresi
        'bipolar': [
            # Bahasa Indonesia - Kata kunci bipolar
            'bipolar', 'mood swing', 'naik turun drastis',
            'kadang semangat kadang drop', 'emosi tidak stabil',
            'manik', 'euphoria lalu sedih', 'ganti mood ekstrem',
            # Bahasa Inggris (unique only)
            'manic', 'mania',
            'euphoric then depressed', 'extreme mood changes'
        ],

        # ==== KATEGORI 6: SKIZOFRENIA ====
        # Gejala: halusinasi, delusi, gangguan persepsi realita
        'schizophrenia': [
            # Bahasa Indonesia - Kata kunci skizofrenia
            'skizofrenia', 'halusinasi', 'dengar suara',
            'delusi', 'waham', 'paranoid',
            # Bahasa Inggris - English keywords
            'schizophrenia', 'hallucination', 'hearing voices',
            'delusion', 'paranoid', 'psychosis'
        ],

        # ==== KATEGORI 7: DUKUNGAN SOSIAL ====
        # Konten: mencari/memberikan dukungan, awareness, kesadaran mental health
        'social_support': [
            # Bahasa Indonesia - Kata kunci dukungan
            'dukungan mental', 'support system', 'curhat',
            'butuh teman bicara', 'sharing', 'konseling',
            'psikolog', 'terapis', 'support group',
            'semangat ya', 'kamu tidak sendiri', 'aku di sini',
            'jangan menyerah', 'tetap kuat', 'mental health awareness',
            # Bahasa Inggris - English keywords
            'mental support', 'support system', 'counseling',
            'therapy', 'therapist', 'psychologist', 'support group',
            "you're not alone", "i'm here", 'stay strong',
            'mental health awareness', 'seeking help'
        ],

        # ==== KATEGORI 8: TERAPI ====
        # Konten: treatment, pengobatan, konseling profesional
        'therapy': [
            # Bahasa Indonesia - Kata kunci terapi
            'terapi', 'konseling', 'psikolog', 'psikiater',
            'obat depresi', 'antidepresan', 'pengobatan mental',
            'rehabilitasi mental', 'treatment', 'cognitive therapy',
            'meditation', 'meditasi', 'mindfulness',
            # Bahasa Inggris - English keywords
            'therapy', 'counseling', 'psychologist', 'psychiatrist',
            'antidepressant', 'medication', 'mental treatment',
            'cognitive behavioral', 'cbt', 'meditation', 'mindfulness'
        ],

        # ==== KATEGORI 9: SUICIDE/SELF-HARM (SENSITIF) ====
        # PERINGATAN: Kategori ini memerlukan penanganan khusus
        # Konten: pemikiran bunuh diri, self-harm, krisis
        'suicide': [
            # Bahasa Indonesia - Kata kunci bunuh diri (SENSITIF)
            'bunuh diri', 'suicide', 'suicidal', 'ingin mati',
            'pengen mati', 'lebih baik mati', 'akhiri hidup',
            'tidak ingin hidup', 'capek hidup', 'tired of life',
            'self harm', 'menyakiti diri', 'melukai diri',
            # Bahasa Inggris
            'suicide', 'suicidal', 'want to die', 'end my life',
            'kill myself', 'self harm', 'cutting', 'hurt myself',
            'better off dead', 'life not worth'
        ],

        'general_mental_health': [
            # Bahasa Indonesia
            'kesehatan mental', 'mental health', 'gangguan jiwa',
            'sakit mental', 'masalah mental', 'gangguan mental',
            'kondisi mental', 'mental illness', 'mental disorder',
            # Bahasa Inggris
            'mental health', 'mental illness', 'mental disorder',
            'psychological', 'psychiatric', 'mental condition'
        ]
    }


    return keywords

# =============================================================================
# SECTION 2.5: SUBJECT DEMOGRAPHICS ANALYSIS
# =============================================================================
# Logika untuk mengklasifikasi user berdasarkan demografi (Remaja vs Dewasa)
# Berdasarkan analisis kalibrasi ulang (Re-Analysis Validation)

# 1. STOPWORDS SLANG (Neutral - Digunakan semua umur)
GENERAL_SLANG_NEUTRAL = [
    'wkwk', 'wkwkwk', 'wk', 'haha', 'hehe', 'huhu',
    'yg', 'yang', 'gak', 'ga', 'nggak', 'enggak',
    'udah', 'udh', 'sudah', 'blm', 'belom',
    'bgt', 'banget', 'aja', 'aj',
    'tapi', 'tp', 'krn', 'karna', 'karena',
    'dr', 'dari', 'sm', 'sama',
    'mau', 'mo', 'mw', 'kalo', 'kl', 'klo',
    'gw', 'gue', 'gua', 'lu', 'lo', 'el',
    'tau', 'temen', 'org', 'orang',
    'bikin', 'buat', 'jd', 'jadi',
    'si', 'sih', 'nih', 'deh', 'dong', 'tuh',
    'iya', 'iye', 'kagak', 'kaga',
    'mas', 'mba', 'mbak', 'kak', 'bang',
    'anjir', 'njir', 'anjing', 'bgst'
]

# 2. INDIKATOR KUAT REMAJA (Gen Z / Sekolah)
TEEN_STRONG_INDICATORS = [
    # Sekolah/Kuliah Awal
    'sekolah', 'guru', 'pr', 'tugas sekolah', 'ujian', 'ulangan',
    'semester', 'krs', 'ipk', 'dosen', 'kampus', 'skripsi', 'mahasiswa',
    'snmptn', 'sbmptn', 'utbk', 'jurusan',

    # Pop Culture / Fandom
    'kpop', 'bias', 'fandom', 'streaming', 'comeback',
    'drakor', 'anime', 'manga', 'webtoon', 'wattpad',
    'wts', 'wtb', 'photocard', 'pc',

    # Slang Spesifik Era 2020-an
    'bestie', 'mengcape', 'nangid', 'ygy', 'fomo', 'overthinking',
    'insecure', 'valid', 'crush', 'confess', 'menfess',
    'spill', 'tea', 'salty', 'cringe', 'red flag', 'green flag',
    'healing', 'self reward', 'jbjb', 'moots', 'mutual',
]

# 3. INDIKATOR KUAT DEWASA (Kerja / Rumah Tangga / Orang Tua)
ADULT_STRONG_INDICATORS = [
    # Pekerjaan & Karir
    'kantor', 'kerjaan', 'lembur', 'meeting', 'rapat', 'dinas',
    'gaji', 'rekening', 'transfer', 'bank', 'cicilan', 'kredit',
    'tagihan', 'listrik', 'token', 'pajak', 'npwp', 'bpjs',
    'hrd', 'boss', 'atasan', 'bawahan', 'klien', 'proyek',
    'bisnis', 'jualan', 'dagang', 'lapak', 'toko',

    # Rumah Tangga & Keluarga
    'suami', 'istri', 'anakku', 'anak-anak', 'si kecil', 'bocil',
    'mertua', 'ipar', 'ponakan', 'sepupu', 'keluarga',
    'nikah', 'kawin', 'rumah tangga', 'dapur', 'masak',
    'belanja bulanan', 'pasar', 'supermarket',

    # Isu Sosial/Politik (Konteks serius)
    'pemerintah', 'kebijakan', 'rakyat', 'masyarakat', 'ekonomi',
    'bansos', 'bantuan', 'korupsi', 'pejabat', 'negara',
    'vaksinasi', 'prokes', 'aturan', 'surat', 'dokumen'
]

# 4. FILTER NON-INDIVIDU (Media/Bot/Gov)
NON_INDIVIDUAL_KEYWORDS = [
    'news', 'berita', 'media', 'official', 'update', 'bot',
    'fess', 'menfess', 'auto', 'base', 'community',
    'loker', 'info', 'tv', 'fm', 'radio',
    'humas', 'admin', 'store', 'shop', 'online'
]

def analyze_subject_category(user: str, text: str) -> Dict:
    """
    Analisis kategori subjek (User Demographics) berdasarkan username dan konten tweet.

    Returns:
        dict: {
            'subject_category': str (REMAJA, DEWASA, INDIVIDU_UMUM, MEDIA_BOT),
            'confidence': str,
            'details': str
        }
    """
    user = str(user).lower()
    text = str(text).lower()

    # 1. Cek Non-Individu berdasarkan Username
    for kw in NON_INDIVIDUAL_KEYWORDS:
        if kw in user:
            return {
                'subject_category': 'MEDIA_BOT',
                'subject_confidence': 'HIGH',
                'subject_details': f'Username keyword: {kw}'
            }

    # 2. Cek Indikator Konten
    teen_matches = [w for w in TEEN_STRONG_INDICATORS if w in text]
    adult_matches = [w for w in ADULT_STRONG_INDICATORS if w in text]

    teen_score = len(teen_matches)
    adult_score = len(adult_matches)

    category = 'INDIVIDU_UMUM'
    confidence = 'LOW'
    details = f"T:{teen_score}, A:{adult_score}"

    if teen_score == 0 and adult_score == 0:
        # Cek slang umum untuk membedakan dengan bot/formal
        general_slang = sum(1 for w in GENERAL_SLANG_NEUTRAL if w in text)
        if general_slang > 0:
            category = 'INDIVIDU_UMUM' # Informal tapi umum
        else:
            category = 'INDIVIDU_UMUM' # Netral

    elif teen_score > adult_score:
        category = 'REMAJA'
        confidence = 'MEDIUM' if teen_score < 3 else 'HIGH'
        details = f"Indicators: {','.join(teen_matches[:3])}"

    elif adult_score > teen_score:
        category = 'DEWASA'
        confidence = 'MEDIUM' if adult_score < 3 else 'HIGH'
        details = f"Indicators: {','.join(adult_matches[:3])}"

    else: # Score sama
        category = 'INDIVIDU_CAMPURAN'

    return {
        'subject_category': category,
        'subject_confidence': confidence,
        'subject_details': details
    }


class MentalHealthFilter:
    """
    Kelas untuk filtering dan labeling konten kesehatan mental.

    Attributes:
        mental_health_keywords (dict): Dictionary kata kunci per kategori
        bert_model: Model BERT untuk analisis kontekstual
        bert_tokenizer: Tokenizer BERT
        threshold_keyword (float): Threshold untuk keyword matching (default: 1)
        threshold_contextual (float): Threshold untuk contextual similarity (default: 0.65)
    """

    def __init__(self,
                 bert_model_name='indolem/indobert-base-uncased',
                 threshold_keyword=1,
                 threshold_contextual=0.65):
        """
        Inisialisasi Mental Health Filter.

        Args:
            bert_model_name (str): Nama model BERT untuk bahasa Indonesia
            threshold_keyword (int): Minimum keyword match untuk dianggap relevan
            threshold_contextual (float): Threshold similarity untuk BERT (0-1)
        """
        print("="*60)
        print("INISIALISASI MENTAL HEALTH FILTER")
        print("="*60)

        self.threshold_keyword = threshold_keyword
        self.threshold_contextual = threshold_contextual

        # 1. Load Mental Health Keywords
        print("\n1. Memuat kata kunci kesehatan mental...")
        self.mental_health_keywords = load_mental_health_keywords()
        print(f"✓ Total {sum(len(v) for v in self.mental_health_keywords.values())} kata kunci dimuat")

        # 2. Load BERT Model untuk contextual understanding
        print("\n2. Memuat model BERT untuk analisis kontekstual...")
        if not BERT_AVAILABLE:
            print("  ⚠ BERT dependencies tidak tersedia")
            print("  Menggunakan keyword matching saja tanpa contextual analysis")
            self.bert_model = None
            self.bert_tokenizer = None
        else:
            try:
                self.bert_tokenizer = AutoTokenizer.from_pretrained(bert_model_name)
                self.bert_model = AutoModel.from_pretrained(bert_model_name)
                self.bert_model.eval()  # Set ke evaluation mode
                print(f"✓ Model BERT '{bert_model_name}' berhasil dimuat")
            except Exception as e:
                print(f"⚠ Gagal memuat BERT: {e}")
                print("  Menggunakan keyword matching saja tanpa contextual analysis")
                self.bert_model = None
                self.bert_tokenizer = None

        # 3. Generate reference embeddings untuk setiap kategori
        if self.bert_model is not None:
            print("\n3. Membuat reference embeddings untuk setiap kategori...")
            self.category_embeddings = self._generate_category_embeddings()
            print(f"✓ Reference embeddings untuk {len(self.category_embeddings)} kategori dibuat")
        else:
            self.category_embeddings = {}

        print("\n✓ Mental Health Filter siap digunakan")
        print("="*60)

    def _generate_category_embeddings(self) -> Dict[str, np.ndarray]:
        """
        Generate BERT embeddings untuk setiap kategori mental health.

        Returns:
            dict: Dictionary dengan kategori sebagai key dan embedding sebagai value
        """
        if self.bert_model is None:
            return {}

        category_embeddings = {}

        for category, keywords in self.mental_health_keywords.items():
            # Gabungkan semua keywords dalam kategori
            category_text = ' '.join(keywords)

            # Generate embedding
            embedding = self._get_bert_embedding(category_text)
            category_embeddings[category] = embedding

        return category_embeddings

    def _get_bert_embedding(self, text: str) -> np.ndarray:
        """
        Dapatkan BERT embedding untuk sebuah teks.

        Args:
            text (str): Teks yang akan di-embed

        Returns:
            np.ndarray: Vector embedding (768 dimensi untuk BERT base)
        """
        if self.bert_model is None:
            return np.zeros(768)

        # Tokenize
        inputs = self.bert_tokenizer(
            text,
            return_tensors='pt',
            truncation=True,
            max_length=512,
            padding=True
        )

        # Generate embedding
        with torch.no_grad():
            outputs = self.bert_model(**inputs)
            # Ambil [CLS] token embedding sebagai representasi teks
            # Use squeeze(0) to only remove the batch dimension
            embedding = outputs.last_hidden_state[:, 0, :].squeeze(0).numpy()

        return embedding

    def check_keyword_match(self, text: str) -> Tuple[bool, List[str], Dict[str, int]]:
        """
        Check apakah teks mengandung kata kunci mental health.

        Args:
            text (str): Teks yang akan dicek

        Returns:
            tuple: (is_match, matched_keywords, category_counts)
                - is_match: True jika ada keyword match
                - matched_keywords: List kata kunci yang match
                - category_counts: Dict jumlah match per kategori
        """
        text_lower = text.lower()
        matched_keywords = []
        category_counts = {}

        for category, keywords in self.mental_health_keywords.items():
            matches = []
            for keyword in keywords:
                if keyword.lower() in text_lower:
                    matches.append(keyword)

            if matches:
                matched_keywords.extend(matches)
                category_counts[category] = len(matches)

        is_match = len(matched_keywords) >= self.threshold_keyword

        return is_match, matched_keywords, category_counts

    def check_contextual_relevance(self, text: str) -> Tuple[bool, str, float]:
        """
        Check relevansi kontekstual menggunakan BERT similarity.

        Args:
            text (str): Teks yang akan dicek

        Returns:
            tuple: (is_relevant, best_category, max_similarity)
                - is_relevant: True jika similarity > threshold
                - best_category: Kategori dengan similarity tertinggi
                - max_similarity: Nilai similarity tertinggi
        """
        if self.bert_model is None or not self.category_embeddings:
            return False, None, 0.0

        # Generate embedding untuk teks
        text_embedding = self._get_bert_embedding(text).reshape(1, -1)

        # Hitung similarity dengan setiap kategori
        max_similarity = 0.0
        best_category = None

        for category, cat_embedding in self.category_embeddings.items():
            cat_embedding = cat_embedding.reshape(1, -1)
            if SKLEARN_AVAILABLE:
                similarity = cosine_similarity(text_embedding, cat_embedding)[0][0]
            else:
                # Fallback to numpy dot product if sklearn not available
                text_norm = np.linalg.norm(text_embedding)
                cat_norm = np.linalg.norm(cat_embedding)

                # Avoid division by zero
                if text_norm == 0 or cat_norm == 0:
                    similarity = 0.0
                else:
                    similarity = np.dot(text_embedding.flatten(), cat_embedding.flatten()) / (
                        text_norm * cat_norm
                    )

            if similarity > max_similarity:
                max_similarity = similarity
                best_category = category

        is_relevant = max_similarity >= self.threshold_contextual

        return is_relevant, best_category, max_similarity

    def classify_mental_health_content(self, text: str) -> Dict:
        """
        Klasifikasi konten berdasarkan keyword dan contextual relevance.

        Args:
            text (str): Teks yang akan diklasifikasi

        Returns:
            dict: Hasil klasifikasi dengan struktur:
                {
                    'is_mental_health_related': bool,
                    'keyword_match': bool,
                    'matched_keywords': list,
                    'category_counts': dict,
                    'contextual_match': bool,
                    'best_category': str,
                    'contextual_score': float,
                    'final_category': str,
                    'confidence': str
                }
        """
        # 1. Keyword matching
        keyword_match, matched_keywords, category_counts = self.check_keyword_match(text)

        # 2. Contextual relevance
        contextual_match, best_category_ctx, contextual_score = self.check_contextual_relevance(text)

        # 3. Determine final classification
        is_mental_health_related = keyword_match or contextual_match

        # Tentukan kategori final
        final_category = None
        confidence = 'low'

        if keyword_match and contextual_match:
            # Kedua metode setuju - confidence tinggi
            # Pilih kategori dengan keyword count tertinggi
            if category_counts:
                final_category = max(category_counts, key=category_counts.get)
            else:
                final_category = best_category_ctx
            confidence = 'high'
        elif keyword_match:
            # Hanya keyword match
            if category_counts:
                final_category = max(category_counts, key=category_counts.get)
            confidence = 'medium'
        elif contextual_match:
            # Hanya contextual match
            final_category = best_category_ctx
            confidence = 'medium'

        return {
            'is_mental_health_related': is_mental_health_related,
            'keyword_match': keyword_match,
            'matched_keywords': matched_keywords,
            'category_counts': category_counts,
            'contextual_match': contextual_match,
            'best_category_contextual': best_category_ctx,
            'contextual_score': float(contextual_score),
            'final_category': final_category,
            'confidence': confidence
        }

    def filter_mental_health_content(self,
                                     df: pd.DataFrame,
                                     text_column: str = None,
                                     user_column: str = None,
                                     target_subject_group: str = None,
                                     batch_size: int = 100) -> pd.DataFrame:
        """
        Filter dataset untuk mengambil hanya konten mental health.

        Args:
            df (pd.DataFrame): DataFrame input
            text_column (str): Nama kolom yang berisi teks (auto-detect jika None)
            user_column (str): Nama kolom username (auto-detect jika None)
            target_subject_group (str): Filter subjects ('REMAJA', 'DEWASA', 'MEDIA_BOT', etc.)
            batch_size (int): Batch size untuk processing (default: 100)

        Returns:
            pd.DataFrame: DataFrame yang sudah difilter dengan kolom tambahan
        """
        print("\n" + "="*60)
        print("FILTERING MENTAL HEALTH CONTENT")
        print("="*60)

        print(f"\n1. Data dimuat: {len(df):,} baris")

        # Auto-detect text column
        if text_column is None:
            possible_cols = ['tweet', 'Tweet', 'text', 'content', 'post_text', 'post']
            for col in possible_cols:
                if col in df.columns:
                    text_column = col
                    break

            if text_column is None:
                raise ValueError(f"Kolom teks tidak ditemukan. Kolom tersedia: {df.columns.tolist()}")

        # Auto-detect user column
        if user_column is None:
            possible_user_cols = ['user', 'User', 'username', 'screen_name', 'author']
            for col in possible_user_cols:
                if col in df.columns:
                    user_column = col
                    break

            if user_column is None:
                # Create dummy user column if not found
                print("⚠ Kolom user tidak ditemukan. Menggunakan 'unknown'.")
                df['temp_user'] = 'unknown'
                user_column = 'temp_user'

        print(f"✓ Menggunakan kolom teks: '{text_column}'")
        print(f"✓ Menggunakan kolom user: '{user_column}'")

        # Clean missing values
        df = df.dropna(subset=[text_column]).reset_index(drop=True)
        print(f"✓ Setelah menghapus missing values: {len(df):,} baris")

        # =========================================================================
        # 1.5 SUBJECT DEMOGRAPHIC ANALYSIS (PRE-FILTERING)
        # =========================================================================
        print("\n2. Melakukan Analisis Demografi Subjek...")

        subject_results = []
        for idx, row in df.iterrows():
            subj_res = analyze_subject_category(row[user_column], row[text_column])
            subject_results.append(subj_res)

        # Add subject columns
        df['subject_category'] = [r['subject_category'] for r in subject_results]
        df['subject_confidence'] = [r['subject_confidence'] for r in subject_results]
        df['subject_details'] = [r['subject_details'] for r in subject_results]

        # Display subject breakdown
        subj_counts = df['subject_category'].value_counts()
        print("\n   Distribusi Subjek:")
        for cat, count in subj_counts.items():
            print(f"   - {cat}: {count:,} ({count/len(df)*100:.1f}%)")

        # =========================================================================
        # STRICT SUBJECT FILTER (HANYA 4 KATEGORI VALID)
        # =========================================================================

        VALID_SUBJECTS = [
            'INDIVIDU_UMUM',
            'INDIVIDU_CAMPURAN',
            'REMAJA',
            'DEWASA'
        ]

        # Hapus semua selain 4 kategori resmi
        before_clean = len(df)
        df = df[df['subject_category'].isin(VALID_SUBJECTS)].reset_index(drop=True)

        print(f"\n✓ Menghapus non-individu (MEDIA_BOT, dll): {before_clean:,} -> {len(df):,} baris")

        # Jika user meminta filter spesifik
        if target_subject_group:
            original_len = len(df)
            print(f"\nCTX: Menerapkan filter subjek utama: '{target_subject_group}'")

            if target_subject_group not in VALID_SUBJECTS:
                print("⚠ Kategori tidak valid!")
                print(f"Gunakan salah satu dari: {VALID_SUBJECTS}")
                return df

            df = df[df['subject_category'] == target_subject_group].reset_index(drop=True)

            print(f"✓ Filter diterapkan: {original_len:,} -> {len(df):,} baris")

            if len(df) == 0:
                print("⚠ Peringatan: Hasil filter kosong!")
                return df

        # =========================================================================
        # END SUBJECT ANALYSIS
        # =========================================================================

        # Process in batches
        print(f"\n3. Memproses konten (Mental Health Check) (batch size: {batch_size})...")
        results = []

        total_batches = (len(df) + batch_size - 1) // batch_size

        for i in range(0, len(df), batch_size):
            batch_num = i // batch_size + 1
            batch = df.iloc[i:i+batch_size]

            print(f"   Batch {batch_num}/{total_batches} ({len(batch)} baris)...", end='\r')

            for idx, row in batch.iterrows():
                text = str(row[text_column])
                classification = self.classify_mental_health_content(text)
                results.append(classification)

        print(f"\n✓ Selesai memproses {len(results):,} baris")

        # Add classification results to dataframe
        print("\n4. Menambahkan hasil klasifikasi ke dataframe...")
        df['mh_is_related'] = [r['is_mental_health_related'] for r in results]
        df['mh_keyword_match'] = [r['keyword_match'] for r in results]
        df['mh_matched_keywords'] = [','.join(r['matched_keywords'][:MAX_KEYWORDS_TO_STORE]) for r in results]
        df['mh_contextual_match'] = [r['contextual_match'] for r in results]
        df['mh_contextual_score'] = [r['contextual_score'] for r in results]
        df['mh_category'] = [r['final_category'] for r in results]
        df['mh_confidence'] = [r['confidence'] for r in results]

        # Filter hanya yang related
        df_filtered = df[df['mh_is_related'] == True].reset_index(drop=True)

        print(f"✓ Kolom klasifikasi ditambahkan")
        print(f"\n5. Hasil Filtering:")
        print(f"   - Total data subjek terpilih: {len(df):,} baris")
        print(f"   - Data mental health: {len(df_filtered):,} baris ({len(df_filtered)/len(df)*100:.2f}%)")
        print(f"   - Data non-mental health: {len(df) - len(df_filtered):,} baris")

        # Statistics
        if len(df_filtered) > 0:
            print(f"\n6. Distribusi Kategori (Mental Health):")
            category_dist = df_filtered['mh_category'].value_counts()
            for cat, count in category_dist.items():
                print(f"   - {cat}: {count:,} ({count/len(df_filtered)*100:.2f}%)")

            print(f"\n7. Distribusi Confidence:")
            conf_dist = df_filtered['mh_confidence'].value_counts()
            for conf, count in conf_dist.items():
                print(f"   - {conf}: {count:,} ({count/len(df_filtered)*100:.2f}%)")

        print("\n" + "="*60)

        return df_filtered

    def save_filtered_data(self, df: pd.DataFrame, output_path: str):
        """
        Simpan data yang sudah difilter.

        Args:
            df (pd.DataFrame): DataFrame yang akan disimpan
            output_path (str): Path output file
        """
        print(f"\nMenyimpan data ke {output_path}...")
        df.to_csv(output_path, index=False, sep='\t')
        print(f"✓ Data disimpan: {len(df):,} baris")

    def generate_filter_report(self, df_original: pd.DataFrame,
                              df_filtered: pd.DataFrame,
                              output_path: str = 'mental_health_filter_report.json'):
        """
        Generate laporan filtering.

        Args:
            df_original (pd.DataFrame): DataFrame asli
            df_filtered (pd.DataFrame): DataFrame yang sudah difilter
            output_path (str): Path untuk menyimpan laporan
        """
        report = {
            'filter_metadata': {
                'timestamp': datetime.now().isoformat(),
                'threshold_keyword': self.threshold_keyword,
                'threshold_contextual': self.threshold_contextual,
                'bert_model': 'indolem/indobert-base-uncased' if self.bert_model else None
            },
            'statistics': {
                'total_original': len(df_original),
                'total_filtered': len(df_filtered),
                'filter_rate': f"{len(df_filtered)/len(df_original)*100:.2f}%"
            },
            'category_distribution': df_filtered['mh_category'].value_counts().to_dict() if len(df_filtered) > 0 else {},
            'confidence_distribution': df_filtered['mh_confidence'].value_counts().to_dict() if len(df_filtered) > 0 else {},
            'method_performance': {
                'keyword_only': int((df_filtered['mh_keyword_match'] & ~df_filtered['mh_contextual_match']).sum()),
                'contextual_only': int((~df_filtered['mh_keyword_match'] & df_filtered['mh_contextual_match']).sum()),
                'both_methods': int((df_filtered['mh_keyword_match'] & df_filtered['mh_contextual_match']).sum())
            }
        }

        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2, ensure_ascii=False)

        print(f"\n✓ Laporan filtering disimpan ke {output_path}")

        return report


# =============================================================================
# SECTION 4: PPKM PREPROCESSOR CLASS
# =============================================================================

# Konstanta untuk mapping sentiment PPKM dataset
# 0 = Netral, 1 = Positif, 2 = Negatif
SENTIMENT_MAP = {
    0: 'Netral',
    1: 'Positif',
    2: 'Negatif'
}


class PPKMPreprocessor:
    """
    Preprocessor untuk dataset PPKM agar siap untuk analisis mental health.
    """

    def __init__(self, data_dir='data'):
        """
        Inisialisasi PPKM Preprocessor.

        Args:
            data_dir (str): Direktori untuk menyimpan data
        """
        self.data_dir = data_dir
        os.makedirs(data_dir, exist_ok=True)

        print("="*60)
        print("PPKM DATASET PREPROCESSOR")
        print("Untuk Analisis Kesehatan Mental")
        print("="*60)

    def process_ppkm_raw(self,
                        df_raw: pd.DataFrame,
                        df_labeled: pd.DataFrame = None,
                        output_filename='INA_TweetsPPKM_MentalHealth_Filtered.csv',
                        use_labeled_sentiment=True):
        """
        Proses lengkap: filter dan convert PPKM dataset.

        PERBAIKAN: Juga memproses INA_TweetsPPKM_Labeled_Pure.csv untuk:
        1. Menggunakan label sentiment asli yang lebih akurat
        2. Mendapatkan distribusi sentiment yang lebih seimbang

        Args:
            df_raw (pd.DataFrame): DataFrame dari INA_TweetsPPKM_Raw.csv
            df_labeled (pd.DataFrame): DataFrame dari INA_TweetsPPKM_Labeled_Pure.csv (optional)
            output_filename (str): Nama file output
            use_labeled_sentiment (bool): Jika True, gunakan sentiment dari labeled file

        Returns:
            pd.DataFrame: DataFrame yang sudah diproses
        """
        print("\n" + "="*60)
        print("TAHAP 1: FILTERING MENTAL HEALTH CONTENT")
        print("="*60)

        # 1. Initialize Mental Health Filter
        print("\nInisialisasi Mental Health Filter...")
        mh_filter = MentalHealthFilter(
            threshold_keyword=1,
            threshold_contextual=0.60  # Sedikit lebih rendah untuk PPKM dataset
        )

        # 2. Load original data (Raw - tanpa sentiment)
        print(f"\nData Raw dimuat: {len(df_raw):,} baris")
        df_original = df_raw.copy()

        # 2b. PERBAIKAN: Load labeled data untuk sentiment
        if df_labeled is not None and use_labeled_sentiment:
            print(f"\nData Labeled dimuat: {len(df_labeled):,} baris")

            # Tampilkan distribusi sentiment asli
            print("\nDistribusi Sentiment Asli (dari Labeled data):")
            sent_dist = df_labeled['sentiment'].value_counts()
            total = len(df_labeled)
            for sent_id, count in sent_dist.items():
                label = SENTIMENT_MAP.get(sent_id, f'Unknown({sent_id})')
                print(f"  {label}: {count:,} ({count/total*100:.2f}%)")

        # 3. Filter mental health content
        df_filtered = mh_filter.filter_mental_health_content(df_original)

        # 3b. PERBAIKAN: Merge sentiment labels dari labeled data
        if df_labeled is not None and use_labeled_sentiment:
            print("\nMenggabungkan sentiment labels dari data labeled...")

            # Merge berdasarkan Tweet text (karena mungkin tidak ada unique ID)
            # PERBAIKAN: Gunakan kombinasi Date + User + Tweet untuk matching yang lebih akurat
            if 'Tweet' in df_filtered.columns and 'Tweet' in df_labeled.columns:
                # Coba merge dengan multiple keys jika tersedia
                if all(col in df_filtered.columns and col in df_labeled.columns for col in ['Date', 'User']):
                    # Merge menggunakan Date + User + Tweet sebagai composite key
                    df_merged = df_filtered.merge(
                        df_labeled[['Date', 'User', 'Tweet', 'sentiment']],
                        on=['Date', 'User', 'Tweet'],
                        how='left',
                        suffixes=('', '_labeled')
                    )
                    df_filtered['sentiment'] = df_merged['sentiment']
                    print("  Menggunakan composite key (Date + User + Tweet) untuk matching")
                else:
                    # Fallback: Create a mapping from Tweet to sentiment
                    tweet_to_sentiment = dict(zip(df_labeled['Tweet'], df_labeled['sentiment']))
                    df_filtered['sentiment'] = df_filtered['Tweet'].map(tweet_to_sentiment)
                    print("  Menggunakan Tweet text saja untuk matching (mungkin kurang akurat)")

                # Hitung matched SEBELUM fillna
                matched = df_filtered['sentiment'].notna().sum()
                unmatched = len(df_filtered) - matched

                # Fill missing dengan DEFAULT_SENTIMENT (netral) sebagai default
                df_filtered['sentiment'] = df_filtered['sentiment'].fillna(DEFAULT_SENTIMENT).astype(int)

                print(f"✓ {matched:,} dari {len(df_filtered):,} tweets berhasil di-match dengan sentiment labels")
                if unmatched > 0:
                    print(f"  ⚠ {unmatched:,} tweets tidak memiliki label, menggunakan default Netral")

                # Tampilkan distribusi sentiment hasil filter
                print("\nDistribusi Sentiment (setelah mental health filtering):")
                sent_dist = df_filtered['sentiment'].value_counts()
                total_filtered = len(df_filtered)
                for sent_id, count in sent_dist.items():
                    label = SENTIMENT_MAP.get(sent_id, f'Unknown({sent_id})')
                    print(f"  {label}: {count:,} ({count/total_filtered*100:.2f}%)")

        # 4. Save filtered data
        output_path = os.path.join(self.data_dir, output_filename)
        mh_filter.save_filtered_data(df_filtered, output_path)

        # 5. Generate filter report
        report_path = os.path.join(self.data_dir, 'mental_health_filter_report.json')
        mh_filter.generate_filter_report(df_original, df_filtered, report_path)

        print("\n" + "="*60)
        print("TAHAP 2: FORMAT CONVERSION")
        print("="*60)

        # 6. Convert to pipeline-compatible format
        df_converted = self.convert_to_pipeline_format(df_filtered)

        # Save converted format
        converted_path = os.path.join(self.data_dir,
                                     output_filename.replace('.csv', '_pipeline_ready.csv'))
        df_converted.to_csv(converted_path, index=False)
        print(f"\n✓ Data pipeline-ready disimpan ke {converted_path}")

        print("\n" + "="*60)
        print("TAHAP 3: VALIDASI DAN SAMPLING")
        print("="*60)

        # 7. Generate sample untuk verifikasi manual
        self.generate_sample_for_verification(df_filtered)

        # 8. Generate preprocessing report
        self.generate_preprocessing_report(df_original, df_filtered, df_converted)

        return df_converted

    def convert_to_pipeline_format(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Konversi format PPKM ke format yang compatible dengan pipeline.

        Pipeline expects:
            - post_created: Timestamp
            - post_text: Teks konten
            - (optional) label: 0 atau 1

        Args:
            df (pd.DataFrame): DataFrame PPKM yang sudah difilter

        Returns:
            pd.DataFrame: DataFrame dalam format pipeline
        """
        print("\nMengkonversi format dataset...")

        df_converted = pd.DataFrame()

        # Map kolom Date -> post_created
        if 'Date' in df.columns:
            df_converted['post_created'] = df['Date']
        elif 'date' in df.columns:
            df_converted['post_created'] = df['date']
        else:
            print("PERINGATAN: Kolom Date tidak ditemukan, menggunakan timestamp sekarang")
            df_converted['post_created'] = datetime.now()

        # Map kolom Tweet -> post_text
        if 'Tweet' in df.columns:
            df_converted['post_text'] = df['Tweet']
        elif 'tweet' in df.columns:
            df_converted['post_text'] = df['tweet']
        elif 'text' in df.columns:
            df_converted['post_text'] = df['text']
        else:
            print("ERROR: Kolom Tweet/text tidak ditemukan!")
            return None

        # Add optional columns if available
        if 'User' in df.columns:
            df_converted['user_id'] = df['User']

        # Add mental health metadata
        if 'mh_category' in df.columns:
            df_converted['mh_category'] = df['mh_category']
            df_converted['mh_confidence'] = df['mh_confidence']
            df_converted['mh_matched_keywords'] = df['mh_matched_keywords']

        # =====================================================================
        # PERBAIKAN: Add subject demographics untuk mencegah duplikasi di pipeline
        # Kolom ini dihasilkan oleh analyze_subject_category() di mental_health_filter
        # =====================================================================
        if 'subject_category' in df.columns:
            df_converted['subject_category'] = df['subject_category']
            print("✓ Subject category (demographics) disertakan")
        if 'subject_confidence' in df.columns:
            df_converted['subject_confidence'] = df['subject_confidence']
        if 'subject_details' in df.columns:
            df_converted['subject_details'] = df['subject_details']

        # PERBAIKAN: Add sentiment labels jika tersedia dari labeled data
        if 'sentiment' in df.columns:
            df_converted['sentiment'] = df['sentiment']
            print("✓ Sentiment labels dari data labeled disertakan")

            # Tampilkan distribusi
            sent_dist = df_converted['sentiment'].value_counts()
            print("  Distribusi sentiment:")
            for sent_id, count in sent_dist.items():
                label = SENTIMENT_MAP.get(sent_id, f'Unknown({sent_id})')
                print(f"    {label}: {count:,}")
        else:
            # Add dummy label (akan diganti dengan sentiment dari BERT)
            # 1 = positive, 0 = negative (placeholder)
            df_converted['label'] = 1
            print("⚠ Sentiment labels tidak tersedia, menggunakan label dummy")

        print(f"✓ Format dikonversi: {len(df_converted):,} baris, {len(df_converted.columns)} kolom")
        print(f"  Kolom: {df_converted.columns.tolist()}")

        return df_converted

    def generate_sample_for_verification(self, df: pd.DataFrame, n_samples=20):
        """
        Generate sample tweets untuk verifikasi manual.

        Args:
            df (pd.DataFrame): DataFrame yang sudah difilter
            n_samples (int): Jumlah sample per kategori
        """
        print(f"\nMembuat sample untuk verifikasi manual ({n_samples} per kategori)...")

        sample_path = os.path.join(self.data_dir, 'sample_filtered_tweets.txt')

        with open(sample_path, 'w', encoding='utf-8') as f:
            f.write("="*80 + "\n")
            f.write("SAMPLE TWEETS UNTUK VERIFIKASI MANUAL\n")
            f.write(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("="*80 + "\n\n")

            # Sample per kategori
            if 'mh_category' in df.columns:
                categories = df['mh_category'].value_counts().index.tolist()

                for category in categories:
                    category_df = df[df['mh_category'] == category]
                    sample_df = category_df.sample(min(n_samples, len(category_df)))

                    f.write(f"\n{'='*80}\n")
                    f.write(f"KATEGORI: {category.upper()}\n")
                    f.write(f"Total: {len(category_df)} tweets\n")
                    f.write(f"{'='*80}\n\n")

                    for seq_num, (idx, row) in enumerate(sample_df.iterrows(), 1):
                        text_col = 'Tweet' if 'Tweet' in row else 'text'
                        f.write(f"{seq_num}. {row[text_col]}\n")
                        f.write(f"   Keywords: {row.get('mh_matched_keywords', 'N/A')}\n")
                        f.write(f"   Confidence: {row.get('mh_confidence', 'N/A')}\n")

                        # Format contextual score safely
                        score = row.get('mh_contextual_score', 0)
                        if isinstance(score, (int, float)):
                            f.write(f"   Contextual Score: {score:.3f}\n")
                        else:
                            f.write(f"   Contextual Score: N/A\n")
                        f.write("\n")

        print(f"✓ Sample disimpan ke {sample_path}")
        print("  Silakan review manual untuk memverifikasi kualitas filtering.")

    def generate_preprocessing_report(self, df_original, df_filtered, df_converted):
        """
        Generate comprehensive preprocessing report.

        Args:
            df_original (pd.DataFrame): Data asli
            df_filtered (pd.DataFrame): Data yang sudah difilter
            df_converted (pd.DataFrame): Data yang sudah dikonversi
        """
        print("\nMembuat laporan preprocessing...")

        report = {
            'metadata': {
                'timestamp': datetime.now().isoformat(),
                'input_file': 'INA_TweetsPPKM_Raw.csv',
                'output_file': 'INA_TweetsPPKM_MentalHealth_Filtered_pipeline_ready.csv'
            },
            'statistics': {
                'original_rows': len(df_original),
                'filtered_rows': len(df_filtered),
                'converted_rows': len(df_converted),
                'filter_rate': f"{len(df_filtered)/len(df_original)*100:.2f}%",
                'data_reduction': f"{(1 - len(df_filtered)/len(df_original))*100:.2f}%"
            },
            'quality_metrics': {
                'category_distribution': df_filtered['mh_category'].value_counts().to_dict() if 'mh_category' in df_filtered.columns else {},
                'confidence_distribution': df_filtered['mh_confidence'].value_counts().to_dict() if 'mh_confidence' in df_filtered.columns else {},
                'high_confidence_ratio': f"{(df_filtered['mh_confidence'] == 'high').sum() / len(df_filtered) * 100:.2f}%" if 'mh_confidence' in df_filtered.columns else 'N/A'
            },
            'pipeline_compatibility': {
                'required_columns': ['post_created', 'post_text'],
                'optional_columns': ['user_id', 'label', 'mh_category'],
                'columns_present': df_converted.columns.tolist(),
                'is_compatible': all(col in df_converted.columns for col in ['post_created', 'post_text'])
            },
            'recommendations': []
        }

        # Add recommendations based on statistics
        filter_rate = len(df_filtered) / len(df_original) * 100
        if filter_rate < 1:
            report['recommendations'].append(
                "Filter rate sangat rendah (<1%). Pertimbangkan untuk menurunkan threshold_contextual atau menambah keywords."
            )
        elif filter_rate < 5:
            report['recommendations'].append(
                "Filter rate rendah (<5%). Dataset PPKM mungkin tidak banyak membahas mental health. Pertimbangkan menggunakan dataset lain yang lebih fokus pada mental health."
            )
        else:
            report['recommendations'].append(
                f"Filter rate baik ({filter_rate:.2f}%). Dataset siap digunakan untuk analisis."
            )

        if 'mh_confidence' in df_filtered.columns:
            high_conf_ratio = (df_filtered['mh_confidence'] == 'high').sum() / len(df_filtered) * 100
            if high_conf_ratio < 30:
                report['recommendations'].append(
                    f"Hanya {high_conf_ratio:.2f}% data dengan confidence tinggi. Pertimbangkan review manual atau fine-tuning threshold."
                )

        # Save report
        report_path = os.path.join(self.data_dir, 'preprocessing_report.json')
        with open(report_path, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2, ensure_ascii=False)

        print(f"✓ Laporan preprocessing disimpan ke {report_path}")

        # Print summary
        print("\n" + "="*60)
        print("SUMMARY PREPROCESSING")
        print("="*60)
        print(f"\nData Original: {report['statistics']['original_rows']:,} baris")
        print(f"Data Filtered: {report['statistics']['filtered_rows']:,} baris ({report['statistics']['filter_rate']})")
        print(f"Data Converted: {report['statistics']['converted_rows']:,} baris")
        print(f"\nPipeline Compatible: {'✓ YA' if report['pipeline_compatibility']['is_compatible'] else '✗ TIDAK'}")

        if report['recommendations']:
            print("\nRekomendasi:")
            for i, rec in enumerate(report['recommendations'], 1):
                print(f"  {i}. {rec}")


# =============================================================================
# SECTION 5: FILE UPLOAD FUNCTIONS FOR COLAB
# =============================================================================

def upload_datasets():
    """
    Upload dataset files menggunakan files.upload() untuk Google Colab.

    Returns:
        tuple: (df_raw, df_labeled) - DataFrames yang di-upload
    """
    if IN_COLAB:
        from google.colab import files

        print("\n" + "="*60)
        print("UPLOAD DATASET FILES")
        print("="*60)

        # Upload Raw file (required)
        print("\n1. Upload INA_TweetsPPKM_Raw.csv (REQUIRED)")
        print("   File ini berisi data tweet mentah untuk difilter.\n")
        uploaded_raw = files.upload()

        df_raw = None
        for filename, content in uploaded_raw.items():
            print(f"   ✓ File diterima: {filename}")
            # Parse CSV dengan tab delimiter
            df_raw = pd.read_csv(io.BytesIO(content), delimiter='\t')
            print(f"   ✓ Data dimuat: {len(df_raw):,} baris")
            break

        if df_raw is None:
            raise ValueError("File Raw tidak di-upload!")

        # Upload Labeled file (optional)
        print("\n2. Upload INA_TweetsPPKM_Labeled_Pure.csv (OPTIONAL)")
        print("   File ini berisi sentiment labels untuk matching.")
        print("   Skip dengan menekan Cancel jika tidak ada.\n")

        df_labeled = None
        try:
            uploaded_labeled = files.upload()
            for filename, content in uploaded_labeled.items():
                print(f"   ✓ File diterima: {filename}")
                df_labeled = pd.read_csv(io.BytesIO(content), delimiter='\t')
                print(f"   ✓ Data dimuat: {len(df_labeled):,} baris")
                break
        except Exception as e:
            print(f"   ⚠ File labeled tidak di-upload atau error: {e}")
            print("   Akan melanjutkan tanpa sentiment labels.")

        return df_raw, df_labeled

    else:
        # Local environment - use file paths
        print("\n" + "="*60)
        print("LOAD DATASET FILES (Local Mode)")
        print("="*60)

        raw_path = 'INA_TweetsPPKM_Raw.csv'
        labeled_path = 'INA_TweetsPPKM_Labeled_Pure.csv'

        df_raw = None
        df_labeled = None

        if os.path.exists(raw_path):
            df_raw = pd.read_csv(raw_path, delimiter='\t')
            print(f"✓ Raw data dimuat dari {raw_path}: {len(df_raw):,} baris")
        else:
            print(f"ERROR: {raw_path} tidak ditemukan!")
            return None, None

        if os.path.exists(labeled_path):
            df_labeled = pd.read_csv(labeled_path, delimiter='\t')
            print(f"✓ Labeled data dimuat dari {labeled_path}: {len(df_labeled):,} baris")
        else:
            print(f"⚠ {labeled_path} tidak ditemukan. Melanjutkan tanpa sentiment labels.")

        return df_raw, df_labeled


def download_results(data_dir='data'):
    """
    Download hasil preprocessing untuk Google Colab.

    Args:
        data_dir (str): Direktori tempat file hasil disimpan
    """
    if IN_COLAB:
        from google.colab import files

        print("\n" + "="*60)
        print("DOWNLOAD HASIL PREPROCESSING")
        print("="*60)

        # Download all generated files
        output_files = [
            os.path.join(data_dir, 'INA_TweetsPPKM_MentalHealth_Filtered.csv'),
            os.path.join(data_dir, 'INA_TweetsPPKM_MentalHealth_Filtered_pipeline_ready.csv'),
            os.path.join(data_dir, 'mental_health_filter_report.json'),
            os.path.join(data_dir, 'preprocessing_report.json'),
            os.path.join(data_dir, 'sample_filtered_tweets.txt')
        ]

        for filepath in output_files:
            if os.path.exists(filepath):
                print(f"Downloading: {filepath}")
                files.download(filepath)
            else:
                print(f"⚠ File tidak ditemukan: {filepath}")
    else:
        print("\nMode lokal - file sudah tersedia di direktori:", data_dir)


# =============================================================================
# SECTION 6: MAIN EXECUTION
# =============================================================================

def main():
    """
    Main function untuk preprocessing PPKM dataset.
    Mendukung Google Colab dengan upload file manual.
    """
    print("\n")
    print("="*80)
    print(" "*20 + "PPKM MENTAL HEALTH FILTER")
    print(" "*15 + "untuk Google Colab Environment")
    print("="*80)

    # Step 1: Upload datasets
    df_raw, df_labeled = upload_datasets()

    if df_raw is None:
        print("\nERROR: Dataset Raw tidak tersedia. Proses dihentikan.")
        return

    # Step 2: Initialize preprocessor
    preprocessor = PPKMPreprocessor(data_dir='data')

    # Step 3: Process PPKM dataset
    print("\n" + "="*80)
    print("MEMULAI PREPROCESSING")
    print("="*80)

    has_labeled = df_labeled is not None

    print(f"\nInput Raw: {len(df_raw):,} baris")
    if has_labeled:
        print(f"Input Labeled: {len(df_labeled):,} baris")
    print("Proses: Filter mental health content + Merge sentiment labels + Convert format")
    print("Output: data/INA_TweetsPPKM_MentalHealth_Filtered_pipeline_ready.csv")

    df_processed = preprocessor.process_ppkm_raw(
        df_raw=df_raw,
        df_labeled=df_labeled,
        output_filename='INA_TweetsPPKM_MentalHealth_Filtered.csv',
        use_labeled_sentiment=has_labeled
    )

    if df_processed is not None:
        print("\n" + "="*80)
        print("PREPROCESSING SELESAI")
        print("="*80)
        print("\nFile Output:")
        print("  1. data/INA_TweetsPPKM_MentalHealth_Filtered.csv")
        print("  2. data/INA_TweetsPPKM_MentalHealth_Filtered_pipeline_ready.csv")
        print("  3. data/mental_health_filter_report.json")
        print("  4. data/preprocessing_report.json")
        print("  5. data/sample_filtered_tweets.txt")

        # Step 4: Download results (Colab only)
        if IN_COLAB:
            print("\n" + "="*80)
            download_results('data')

        print("\nLangkah Selanjutnya:")
        print("  1. Review sample_filtered_tweets.txt untuk verifikasi manual")
        print("  2. Jika sudah OK, jalankan pipeline utama:")
        print("     python forecasting_sentiment_gnn_lstm_bert_fix_error_last_category.py")
        print("     dengan data: data/INA_TweetsPPKM_MentalHealth_Filtered_pipeline_ready.csv")
    else:
        print("\nPreprocessing gagal. Periksa error di atas.")


# =============================================================================
# SECTION 7: DEMO FUNCTIONS
# =============================================================================

def demo_keyword_matching():
    """
    Demo: Keyword Matching
    """
    print("\n" + "="*80)
    print("DEMO: KEYWORD MATCHING")
    print("="*80)

    # Sample tweets untuk testing
    test_tweets = [
        # Mental Health Related
        ("Saya merasa depresi dan sedih sekali hari ini", True, "depression"),
        ("Cemas dan khawatir terus, tidak bisa tidur", True, "anxiety"),
        ("Stress kerja membuat saya burnout total", True, "stress"),
        ("Butuh dukungan mental, ada yang bisa curhat?", True, "social_support"),
        ("Trauma masa lalu masih menghantui saya", True, "ptsd"),

        # Not Mental Health Related
        ("Cuaca cerah hari ini, saya pergi jalan-jalan", False, None),
        ("PPKM level 3 diberlakukan di Jakarta", False, None),
        ("Harga sembako naik lagi bulan ini", False, None),
    ]

    # Initialize filter
    mh_filter = MentalHealthFilter(
        threshold_keyword=1,
        threshold_contextual=0.60
    )

    # Test each tweet
    print(f"\nMengetes {len(test_tweets)} tweets...\n")

    correct = 0
    total = len(test_tweets)

    for i, (tweet, expected_match, expected_category) in enumerate(test_tweets, 1):
        result = mh_filter.classify_mental_health_content(tweet)

        is_correct = result['is_mental_health_related'] == expected_match
        if is_correct:
            correct += 1

        status = "✓" if is_correct else "✗"

        print(f"{i}. {status} {tweet}")
        print(f"   Expected: {expected_match} ({expected_category})")
        print(f"   Got: {result['is_mental_health_related']} ({result['final_category']})")
        print(f"   Confidence: {result['confidence']}")

        if result['matched_keywords']:
            print(f"   Keywords: {', '.join(result['matched_keywords'][:3])}")

        print()

    accuracy = (correct / total) * 100
    print(f"\nAkurasi Keyword Matching: {correct}/{total} ({accuracy:.1f}%)")


def demo_csv_filtering():
    """
    Demo: CSV Filtering Simulation
    """
    print("\n" + "="*80)
    print("DEMO: CSV FILTERING SIMULATION")
    print("="*80)

    # Create sample CSV data
    sample_data = {
        'Date': ['2022-03-31'] * 10,
        'User': ['user1', 'user2', 'user3', 'user4', 'user5',
                 'user6', 'user7', 'user8', 'user9', 'user10'],
        'Tweet': [
            "Saya merasa depresi dan tidak ada yang peduli",  # MH
            "PPKM level 3 diberlakukan mulai hari ini",       # Non-MH
            "Cemas terus, tidak bisa tidur malam",            # MH
            "Harga minyak goreng naik lagi",                  # Non-MH
            "Stress kerja bikin burnout total",               # MH
            "Cuaca cerah hari ini",                           # Non-MH
            "Butuh dukungan mental untuk hadapi masalah ini", # MH
            "Liburan ke Bali akhir pekan",                    # Non-MH
            "Trauma masa lalu masih menghantui",              # MH
            "Makan siang enak hari ini"                       # Non-MH
        ]
    }

    df = pd.DataFrame(sample_data)

    print(f"\nTotal tweets: {len(df)}")
    print("\nContoh tweets:")
    for i, row in df.head(5).iterrows():
        print(f"  {i+1}. {row['Tweet']}")

    # Simulate filtering
    print("\nMelakukan filtering mental health content...")

    mh_filter = MentalHealthFilter(threshold_keyword=1)

    results = []
    for tweet in df['Tweet']:
        result = mh_filter.classify_mental_health_content(tweet)
        results.append(result)

    # Add results to dataframe
    df['mh_is_related'] = [r['is_mental_health_related'] for r in results]
    df['mh_category'] = [r['final_category'] for r in results]
    df['mh_confidence'] = [r['confidence'] for r in results]

    # Filter only MH related
    df_filtered = df[df['mh_is_related'] == True]

    print(f"\n✓ Filtering selesai!")
    print(f"  - Total original: {len(df)} tweets")
    print(f"  - Mental health: {len(df_filtered)} tweets ({len(df_filtered)/len(df)*100:.1f}%)")
    print(f"  - Non-mental health: {len(df) - len(df_filtered)} tweets")

    if len(df_filtered) > 0:
        print(f"\nDistribusi Kategori:")
        for cat, count in df_filtered['mh_category'].value_counts().items():
            print(f"  - {cat}: {count} tweets")


def run_demo():
    """
    Run all demos
    """
    print("\n")
    print("="*80)
    print(" "*20 + "MENTAL HEALTH FILTER DEMO")
    print("="*80)

    print("\nDemo ini menunjukkan kemampuan Mental Health Filter:")
    print("  1. Keyword Matching")
    print("  2. CSV Filtering")

    demo_keyword_matching()
    demo_csv_filtering()

    print("\n" + "="*80)
    print("DEMO SELESAI")
    print("="*80)


# =============================================================================
# EXECUTION
# =============================================================================

if __name__ == "__main__":
    # Uncomment the function you want to run:

    # Option 1: Run full preprocessing pipeline
    main()

    # Option 2: Run demo only
    # run_demo()