# -*- coding: utf-8 -*-
"""evaluasi model yassa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-HGcCLLnFf1AtHjiSBqaZjRWCdt02ir
"""

# =============================================================================
# UJI COBA SISTEM - IMPROVED VERSION dengan Data Balancing
# =============================================================================
#
# PERBAIKAN BERDASARKAN SARAN ERIC:
# 1. Back Translation untuk Augmentasi Data (menggunakan deep-translator)
# 2. Hybrid Sampling (Under-sampling + Over-sampling)
# 3. Visualisasi Distribusi Data (sebelum & sesudah balancing)
# 4. Re-training dengan data seimbang
#
# Isu Utama: Imbalanced Dataset menyebabkan model hanya pintar memprediksi
#            kelas mayoritas (High) tapi gagal di kelas minoritas (Medium/Low)
# =============================================================================

# Install dependencies
import subprocess
import sys

def install_packages():
    packages = [
        'pandas', 'numpy', 'scikit-learn',
        'transformers', 'torch', 'sentencepiece', 'accelerate',
        'gensim', 'nltk',
        'networkx',
        'tensorflow',
        'plotly', 'matplotlib', 'seaborn',
        'tqdm',
        'deep-translator'  # BARU: Untuk Back Translation
    ]
    for pkg in packages:
        try:
            subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', pkg])
        except:
            print(f"Warning: Failed to install {pkg}")

install_packages()
print("✓ Dependencies terinstall")

# =============================================================================
# IMPORT LIBRARIES
# =============================================================================

import os
import json
import pickle
import warnings
from datetime import datetime, timedelta
from collections import Counter, defaultdict
import random

# Data processing
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Sentiment Analysis
import torch
from transformers import pipeline as transformers_pipeline

# LSTM
from tensorflow import keras
from tensorflow.keras.models import Sequential, load_model, Model
from tensorflow.keras.layers import (LSTM, Dense, Dropout, BatchNormalization,
                                      Bidirectional, Input, Embedding,
                                      RepeatVector, Concatenate)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from sklearn.preprocessing import MinMaxScaler, RobustScaler, LabelEncoder

# Evaluasi Model
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                            f1_score, confusion_matrix, classification_report)

# Visualisasi
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

# Back Translation - BARU
try:
    from deep_translator import GoogleTranslator
    BACK_TRANSLATION_AVAILABLE = True
    print("✓ deep-translator tersedia untuk Back Translation")
except ImportError:
    BACK_TRANSLATION_AVAILABLE = False
    print("⚠ deep-translator tidak tersedia, akan menggunakan strategi alternatif")

# Google Colab support
try:
    from google.colab import drive, files
    RUNNING_IN_COLAB = True
except ImportError:
    RUNNING_IN_COLAB = False

# Nonaktifkan warnings
warnings.filterwarnings('ignore')

# Download NLTK data
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)

print("✓ All libraries imported successfully")
print(f"✓ Running in Colab: {RUNNING_IN_COLAB}")
print(f"✓ Back Translation Available: {BACK_TRANSLATION_AVAILABLE}")

from google.colab import files
files.upload()

!mkdir -p MentalTrendAI_Output/processed_data
!mv full_preprocessed_data.csv MentalTrendAI_Output/processed_data/

# =============================================================================
# LOAD DATA DAN CEK DISTRIBUSI AWAL
# =============================================================================

import os
import pandas as pd
import matplotlib.pyplot as plt

# Path ke data yang sudah dipreprocess
DATA_PATH = 'MentalTrendAI_Output/processed_data/full_preprocessed_data.csv'
OUTPUT_DIR = 'MentalTrendAI_Output'
VIS_DIR = os.path.join(OUTPUT_DIR, 'visualizations')

# Load data
print("Loading data...")
df = pd.read_csv(DATA_PATH)
print(f"✓ Data loaded: {len(df):,} rows, {len(df.columns)} columns")

# Tampilkan kolom yang tersedia
print(f"\nKolom yang tersedia:")
for col in df.columns:
    print(f"  - {col}")

# Cek distribusi sentiment_category (target untuk klasifikasi)
print("\n" + "="*60)
print("DISTRIBUSI AWAL - SENTIMENT CATEGORY")
print("="*60)
sentiment_dist = df['sentiment_category'].value_counts()
print(sentiment_dist)
print(f"\nTotal: {len(df):,}")

# ================= BUAT FOLDER OUTPUT =================
os.makedirs(VIS_DIR, exist_ok=True)

# =============================================================================
# VISUALISASI DISTRIBUSI (BAR CHART SAJA)
# =============================================================================

plt.figure(figsize=(8, 5))

colors = ['#2ecc71', '#e74c3c', '#3498db']  # Positif, Negatif, Netral

ax = sentiment_dist.plot(
    kind='bar',
    color=colors,
    edgecolor='black'
)

plt.title('Distribusi Sentiment Category (SEBELUM Balancing)',
          fontsize=14, fontweight='bold')
plt.xlabel('Sentiment Category', fontsize=12)
plt.ylabel('Jumlah Data', fontsize=12)
plt.xticks(rotation=0)

# Tambahkan label angka di atas bar
for i, (category, count) in enumerate(sentiment_dist.items()):
    plt.text(i, count + 100, f'{count:,}',
             ha='center', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig(f'{VIS_DIR}/distribusi_sebelum_balancing.png',
            dpi=150, bbox_inches='tight')
plt.show()

# =============================================================================
# ANALISIS IMBALANCE
# =============================================================================

max_class = sentiment_dist.idxmax()
min_class = sentiment_dist.idxmin()

print(f"\n📊 ANALISIS IMBALANCE:")
print(f"  • Kelas Mayoritas: {max_class} ({sentiment_dist[max_class]:,} data)")
print(f"  • Kelas Minoritas: {min_class} ({sentiment_dist[min_class]:,} data)")
print(f"  • Rasio Imbalance: {sentiment_dist[max_class] / sentiment_dist[min_class]:.1f}x")
print(f"\n⚠️  Imbalance ini menyebabkan model cenderung memprediksi kelas {max_class}!")

# =============================================================================
# BACK TRANSLATION - DATA AUGMENTATION
# =============================================================================

import time

class BackTranslationAugmenter:
    """
    Kelas untuk melakukan augmentasi data teks menggunakan Back Translation.

    Alur:
    1. Teks Indonesia → Translate ke Inggris
    2. Teks Inggris → Translate balik ke Indonesia

    Hasilnya adalah variasi kalimat baru dengan makna serupa.
    """

    def __init__(self):
        if BACK_TRANSLATION_AVAILABLE:
            self.translator_id_to_en = GoogleTranslator(source='id', target='en')
            self.translator_en_to_id = GoogleTranslator(source='en', target='id')
        else:
            self.translator_id_to_en = None
            self.translator_en_to_id = None

    def back_translate(self, text, delay=0.5):
        """
        Melakukan back translation pada satu teks.

        Args:
            text: Teks asli dalam bahasa Indonesia
            delay: Delay antar request untuk menghindari rate limiting

        Returns:
            str: Teks hasil back translation (variasi baru)
        """
        if not BACK_TRANSLATION_AVAILABLE or not text or len(text.strip()) < 5:
            return text

        try:
            # Step 1: Translate ID → EN
            english_text = self.translator_id_to_en.translate(text)
            time.sleep(delay)

            # Step 2: Translate EN → ID (back translation)
            back_translated = self.translator_en_to_id.translate(english_text)
            time.sleep(delay)

            return back_translated
        except Exception as e:
            # Jika gagal, kembalikan teks asli
            return text

    def augment_dataframe(self, df, text_column='processed_text', target_column='sentiment_category',
                          minority_classes=None, target_count=None, max_augment_per_class=1000):
        """
        Augmentasi DataFrame dengan back translation untuk kelas minoritas.

        Args:
            df: DataFrame original
            text_column: Nama kolom teks yang akan di-augment
            target_column: Nama kolom target (label)
            minority_classes: List kelas yang akan di-augment (jika None, deteksi otomatis)
            target_count: Target jumlah data per kelas (jika None, samakan dengan mayoritas)
            max_augment_per_class: Maksimum augmentasi per kelas

        Returns:
            DataFrame: DataFrame dengan data augmented
        """
        print("\n" + "="*60)
        print("BACK TRANSLATION - DATA AUGMENTATION")
        print("="*60)

        # Hitung distribusi
        class_counts = df[target_column].value_counts()
        print(f"Distribusi awal:\n{class_counts}\n")

        # Tentukan kelas minoritas jika tidak disediakan
        if minority_classes is None:
            # Anggap semua kelas dengan count < 80% dari max adalah minoritas
            max_count = class_counts.max()
            minority_classes = class_counts[class_counts < max_count * 0.8].index.tolist()

        if not minority_classes:
            print("✓ Tidak ada kelas minoritas yang perlu di-augment")
            return df

        print(f"Kelas minoritas yang akan di-augment: {minority_classes}")

        # Target count (default: samakan dengan 80% mayoritas)
        if target_count is None:
            target_count = int(class_counts.max() * 0.8)

        print(f"Target count per kelas: {target_count:,}")

        augmented_rows = []

        for minority_class in minority_classes:
            current_count = class_counts[minority_class]
            need_augment = min(target_count - current_count, max_augment_per_class)

            if need_augment <= 0:
                continue

            print(f"\nMengaugment kelas '{minority_class}'...")
            print(f"  Current: {current_count:,}, Need: {need_augment:,}")

            # Ambil data dari kelas minoritas
            minority_data = df[df[target_column] == minority_class]

            # Random sample untuk di-augment (bisa repeat jika data sedikit)
            samples = minority_data.sample(n=need_augment, replace=True, random_state=42)

            augmented_count = 0
            for idx, row in tqdm(samples.iterrows(), total=len(samples), desc=f"  Augmenting {minority_class}"):
                original_text = row[text_column]

                # Back translate
                augmented_text = self.back_translate(original_text)

                # Jika hasil berbeda dari aslinya, tambahkan
                if augmented_text and augmented_text != original_text:
                    new_row = row.copy()
                    new_row[text_column] = augmented_text
                    new_row['is_augmented'] = True  # Tandai sebagai augmented
                    augmented_rows.append(new_row)
                    augmented_count += 1

            print(f"  ✓ Berhasil augment {augmented_count:,} data untuk '{minority_class}'")

        # Gabungkan dengan data asli
        if augmented_rows:
            df_augmented = pd.concat([df, pd.DataFrame(augmented_rows)], ignore_index=True)
            df_augmented['is_augmented'] = df_augmented['is_augmented'].fillna(False)

            print(f"\n✓ Total data setelah augmentasi: {len(df_augmented):,}")
            print(f"  Data asli: {len(df):,}")
            print(f"  Data augmented: {len(augmented_rows):,}")

            return df_augmented
        else:
            df['is_augmented'] = False
            return df


# Inisialisasi augmenter
augmenter = BackTranslationAugmenter()

# Cek apakah back translation tersedia
if BACK_TRANSLATION_AVAILABLE:
    # Test back translation dengan contoh
    test_text = "saya merasa sangat sedih dan kesepian hari ini"
    print(f"\n📝 Test Back Translation:")
    print(f"  Original: {test_text}")
    result = augmenter.back_translate(test_text)
    print(f"  Back-translated: {result}")
else:
    print("\n⚠️ Back Translation tidak tersedia. Akan menggunakan strategi alternatif.")

# =============================================================================
# HYBRID SAMPLING - BALANCED DATASET
# =============================================================================

class HybridSampler:
    """
    Kelas untuk melakukan Hybrid Sampling (Under-sampling + Over-sampling).

    Strategi:
    1. Under-sampling: Kurangi kelas mayoritas ke target count
    2. Over-sampling: Tambah kelas minoritas ke target count (dengan random duplication)
    """

    def __init__(self, augmenter=None):
        """
        Args:
            augmenter: BackTranslationAugmenter instance untuk augmentasi (opsional)
        """
        self.augmenter = augmenter

    def balance_dataset(self, df, target_column='sentiment_category',
                        target_count=None, use_back_translation=False,
                        text_column='processed_text'):
        """
        Balance dataset menggunakan hybrid sampling.

        Args:
            df: DataFrame original
            target_column: Kolom target (label)
            target_count: Target jumlah per kelas (None = median)
            use_back_translation: Gunakan back translation untuk over-sampling
            text_column: Kolom teks untuk back translation

        Returns:
            DataFrame: Balanced dataset
        """
        print("\n" + "="*60)
        print("HYBRID SAMPLING - BALANCING DATASET")
        print("="*60)

        # Hitung distribusi awal
        class_counts = df[target_column].value_counts()
        print(f"\nDistribusi SEBELUM balancing:")
        for cls, cnt in class_counts.items():
            print(f"  • {cls}: {cnt:,}")

        # Tentukan target count
        if target_count is None:
            # Gunakan nilai median sebagai target
            target_count = int(class_counts.median())

        print(f"\n🎯 Target count per kelas: {target_count:,}")

        balanced_dfs = []

        for class_name in class_counts.index:
            class_df = df[df[target_column] == class_name].copy()
            current_count = len(class_df)

            if current_count > target_count:
                # UNDER-SAMPLING: Kurangi kelas mayoritas
                print(f"\n[UNDER-SAMPLING] {class_name}: {current_count:,} → {target_count:,}")
                sampled_df = class_df.sample(n=target_count, random_state=42)
                sampled_df['sampling_method'] = 'undersampled'
                balanced_dfs.append(sampled_df)

            elif current_count < target_count:
                # OVER-SAMPLING: Tambah kelas minoritas
                need_more = target_count - current_count
                print(f"\n[OVER-SAMPLING] {class_name}: {current_count:,} → {target_count:,} (+{need_more:,})")

                if use_back_translation and self.augmenter and BACK_TRANSLATION_AVAILABLE:
                    # Gunakan back translation untuk augmentasi
                    print("  → Menggunakan Back Translation...")
                    class_df['sampling_method'] = 'original'

                    # Sample untuk di-augment
                    samples_to_augment = class_df.sample(n=need_more, replace=True, random_state=42)
                    augmented_rows = []

                    for idx, row in tqdm(samples_to_augment.iterrows(),
                                        total=len(samples_to_augment),
                                        desc=f"  Augmenting {class_name}"):
                        new_row = row.copy()
                        # Coba back translation, jika gagal duplikat saja
                        new_text = self.augmenter.back_translate(row[text_column], delay=0.3)
                        new_row[text_column] = new_text if new_text else row[text_column]
                        new_row['sampling_method'] = 'augmented_bt'
                        augmented_rows.append(new_row)

                    augmented_df = pd.DataFrame(augmented_rows)
                    combined_df = pd.concat([class_df, augmented_df], ignore_index=True)
                    balanced_dfs.append(combined_df)
                else:
                    # Random duplication (fallback)
                    print("  → Menggunakan Random Duplication...")
                    class_df['sampling_method'] = 'original'

                    # Random sample dengan replacement
                    extra_samples = class_df.sample(n=need_more, replace=True, random_state=42).copy()
                    extra_samples['sampling_method'] = 'duplicated'

                    combined_df = pd.concat([class_df, extra_samples], ignore_index=True)
                    balanced_dfs.append(combined_df)
            else:
                # Tepat sama dengan target
                print(f"\n[OK] {class_name}: {current_count:,} (sudah seimbang)")
                class_df['sampling_method'] = 'original'
                balanced_dfs.append(class_df)

        # Gabungkan semua kelas
        balanced_df = pd.concat(balanced_dfs, ignore_index=True)

        # Shuffle data
        balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

        # Report hasil
        print("\n" + "-"*40)
        print("HASIL HYBRID SAMPLING:")
        print("-"*40)
        final_dist = balanced_df[target_column].value_counts()
        for cls, cnt in final_dist.items():
            print(f"  • {cls}: {cnt:,}")
        print(f"\n✓ Total data setelah balancing: {len(balanced_df):,}")
        print(f"  • Original: {len(balanced_df[balanced_df['sampling_method'] == 'original']):,}")
        print(f"  • Undersampled: {len(balanced_df[balanced_df['sampling_method'] == 'undersampled']):,}")
        print(f"  • Duplicated: {len(balanced_df[balanced_df['sampling_method'] == 'duplicated']):,}")
        if 'augmented_bt' in balanced_df['sampling_method'].values:
            print(f"  • Augmented (BT): {len(balanced_df[balanced_df['sampling_method'] == 'augmented_bt']):,}")

        return balanced_df


# Inisialisasi sampler
sampler = HybridSampler(augmenter=augmenter)

# Tentukan target count berdasarkan data
class_counts = df['sentiment_category'].value_counts()
median_count = int(class_counts.median())
print(f"\n📊 Statistik kelas:")
print(f"  • Min: {class_counts.min():,}")
print(f"  • Max: {class_counts.max():,}")
print(f"  • Median: {median_count:,}")
print(f"\n→ Akan menggunakan target count = {median_count:,} (median)")

# =============================================================================
# EKSEKUSI HYBRID SAMPLING
# =============================================================================

# Jalankan balancing
df_balanced = sampler.balance_dataset(
    df,
    target_column='sentiment_category',
    target_count=median_count,
    use_back_translation=False,
    text_column='processed_text'
)

# =============================================================================
# VISUALISASI PERBANDINGAN SEBELUM vs SESUDAH BALANCING
# =============================================================================

print("\n" + "="*60)
print("VISUALISASI DISTRIBUSI: SEBELUM vs SESUDAH BALANCING")
print("="*60)

# Tetap pakai subplot supaya struktur tidak berubah
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Warna kategori
colors = ['#2ecc71', '#e74c3c', '#3498db']

# ================= SEBELUM BALANCING =================
ax1 = axes[0]
dist_before = df['sentiment_category'].value_counts()

dist_before.plot(
    kind='bar',
    ax=ax1,
    color=colors,
    edgecolor='black'
)

ax1.set_title('SEBELUM Balancing', fontsize=14, fontweight='bold', color='red')
ax1.set_xlabel('Sentiment Category', fontsize=12)
ax1.set_ylabel('Jumlah Data', fontsize=12)
ax1.tick_params(axis='x', rotation=0)

# Label angka
for i, (cat, cnt) in enumerate(dist_before.items()):
    ax1.text(i, cnt + 100, f'{cnt:,}',
             ha='center', fontsize=10, fontweight='bold')

# Garis target median
ax1.axhline(
    y=median_count,
    color='green',
    linestyle='--',
    linewidth=2,
    label=f'Target: {median_count:,}'
)
ax1.legend()


# ================= SESUDAH BALANCING =================
ax2 = axes[1]
dist_after = df_balanced['sentiment_category'].value_counts()

dist_after.plot(
    kind='bar',
    ax=ax2,
    color=colors,
    edgecolor='black'
)

ax2.set_title('SESUDAH Balancing', fontsize=14, fontweight='bold', color='green')
ax2.set_xlabel('Sentiment Category', fontsize=12)
ax2.set_ylabel('Jumlah Data', fontsize=12)
ax2.tick_params(axis='x', rotation=0)

# Label angka
for i, (cat, cnt) in enumerate(dist_after.items()):
    ax2.text(i, cnt + 50, f'{cnt:,}',
             ha='center', fontsize=10, fontweight='bold')

# Garis target median
ax2.axhline(
    y=median_count,
    color='green',
    linestyle='--',
    linewidth=2,
    label=f'Target: {median_count:,}'
)
ax2.legend()


plt.suptitle(
    'Perbandingan Distribusi Data: Sebelum vs Sesudah Hybrid Sampling',
    fontsize=16,
    fontweight='bold'
)

plt.tight_layout()
plt.savefig(
    f'{OUTPUT_DIR}/visualizations/perbandingan_distribusi_balancing.png',
    dpi=150,
    bbox_inches='tight'
)
plt.show()

# =============================================================================
# REPORT IMBALANCE
# =============================================================================

print("\n📊 PERBANDINGAN IMBALANCE RATIO:")

ratio_before = dist_before.max() / dist_before.min()
ratio_after = dist_after.max() / dist_after.min()

print(f"  • SEBELUM: {ratio_before:.2f}x (imbalanced)")
print(f"  • SESUDAH: {ratio_after:.2f}x (balanced)")
print(f"  • Improvement: {((ratio_before - ratio_after) / ratio_before * 100):.1f}% lebih seimbang")

# =============================================================================
# IMPROVED LSTM MODEL TRAINING DENGAN DATA BALANCED
# =============================================================================

# Konfigurasi LSTM
LSTM_CONFIG = {
    'LSTM_UNITS': [128, 64, 32],
    'DROPOUT_RATES': [0.15, 0.15, 0.1],
    'LEARNING_RATE': 0.001,
    'EARLY_STOPPING_PATIENCE': 30,
    'REDUCE_LR_PATIENCE': 15,
    'MAX_EPOCHS': 100,
    'BATCH_SIZE': 32
}

class ImprovedLSTMClassifier:
    """
    LSTM Classifier untuk klasifikasi risiko kesehatan mental.
    Dioptimalkan untuk data balanced.
    """

    def __init__(self, output_dir='MentalTrendAI_Output'):
        self.output_dir = output_dir
        self.model_dir = os.path.join(output_dir, 'models')
        self.viz_dir = os.path.join(output_dir, 'visualizations')
        self.eval_dir = os.path.join(output_dir, 'evaluations')

        os.makedirs(self.model_dir, exist_ok=True)
        os.makedirs(self.viz_dir, exist_ok=True)
        os.makedirs(self.eval_dir, exist_ok=True)

        self.model = None
        self.scaler = MinMaxScaler()
        self.label_encoder = LabelEncoder()
        self.history = None

    def prepare_features(self, df, target_column='sentiment_category'):
        """
        Prepare features untuk LSTM training.
        Mengekstrak fitur dari data teks dan temporal.
        """
        print("\n📊 Preparing features...")

        # Encode target
        df['target_encoded'] = self.label_encoder.fit_transform(df[target_column])

        # Feature engineering
        features = []

        # 1. Sentiment score (jika ada)
        if 'sentiment_score' in df.columns:
            features.append('sentiment_score')

        # 2. Temporal features (jika ada)
        if 'hour' in df.columns:
            features.append('hour')
        if 'weekday' in df.columns:
            features.append('weekday')
        if 'month' in df.columns:
            features.append('month')

        # 3. Text length feature
        if 'processed_text' in df.columns:
            df['text_length'] = df['processed_text'].apply(lambda x: len(str(x).split()) if pd.notna(x) else 0)
            features.append('text_length')

        # 4. Sentiment numeric (convert dari label)
        if 'sentiment' in df.columns:
            features.append('sentiment')

        # Jika tidak ada fitur cukup, buat fitur dari text
        if len(features) < 3:
            print("  → Membuat fitur tambahan dari teks...")
            df['word_count'] = df['processed_text'].apply(lambda x: len(str(x).split()) if pd.notna(x) else 0)
            df['char_count'] = df['processed_text'].apply(lambda x: len(str(x)) if pd.notna(x) else 0)
            features.extend(['word_count', 'char_count'])

        print(f"  ✓ Features used: {features}")

        X = df[features].fillna(0).values
        y = df['target_encoded'].values

        # Scale features
        X_scaled = self.scaler.fit_transform(X)

        return X_scaled, y, features

    def build_model(self, input_shape, num_classes):
        """
        Build LSTM model architecture.
        """
        print(f"\n🏗️ Building LSTM model...")
        print(f"  Input shape: {input_shape}")
        print(f"  Output classes: {num_classes}")

        model = Sequential([
            # Reshape untuk LSTM (samples, timesteps, features)
            keras.layers.Reshape((1, input_shape), input_shape=(input_shape,)),

            # LSTM Layer 1 - Bidirectional
            Bidirectional(LSTM(
                LSTM_CONFIG['LSTM_UNITS'][0],
                return_sequences=True,
                kernel_regularizer=l2(0.0001)
            )),
            BatchNormalization(),
            Dropout(LSTM_CONFIG['DROPOUT_RATES'][0]),

            # LSTM Layer 2 - Bidirectional
            Bidirectional(LSTM(
                LSTM_CONFIG['LSTM_UNITS'][1],
                return_sequences=True,
                kernel_regularizer=l2(0.0001)
            )),
            BatchNormalization(),
            Dropout(LSTM_CONFIG['DROPOUT_RATES'][1]),

            # LSTM Layer 3
            LSTM(
                LSTM_CONFIG['LSTM_UNITS'][2],
                return_sequences=False,
                kernel_regularizer=l2(0.0001)
            ),
            BatchNormalization(),
            Dropout(LSTM_CONFIG['DROPOUT_RATES'][2]),

            # Dense layers
            Dense(64, activation='relu'),
            Dropout(0.1),
            Dense(32, activation='relu'),

            # Output layer - Classification
            Dense(num_classes, activation='softmax')
        ])

        # Compile dengan class weights untuk handle remaining imbalance
        model.compile(
            optimizer=Adam(learning_rate=LSTM_CONFIG['LEARNING_RATE']),
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy']
        )

        model.summary()
        return model

    def train(self, X_train, y_train, X_val, y_val):
        """
        Train LSTM model.
        """
        print("\n🚀 Training LSTM model...")

        # Hitung class weights untuk handle slight imbalance
        class_counts = np.bincount(y_train)
        total = len(y_train)
        class_weights = {i: total / (len(class_counts) * count) for i, count in enumerate(class_counts)}
        print(f"  Class weights: {class_weights}")

        # Callbacks
        callbacks = [
            keras.callbacks.EarlyStopping(
                monitor='val_loss',
                patience=LSTM_CONFIG['EARLY_STOPPING_PATIENCE'],
                restore_best_weights=True,
                verbose=1
            ),
            keras.callbacks.ReduceLROnPlateau(
                monitor='val_loss',
                factor=0.5,
                patience=LSTM_CONFIG['REDUCE_LR_PATIENCE'],
                min_lr=1e-6,
                verbose=1
            )
        ]

        # Build model
        input_shape = X_train.shape[1]
        num_classes = len(np.unique(y_train))
        self.model = self.build_model(input_shape, num_classes)

        # Training
        self.history = self.model.fit(
            X_train, y_train,
            validation_data=(X_val, y_val),
            epochs=LSTM_CONFIG['MAX_EPOCHS'],
            batch_size=LSTM_CONFIG['BATCH_SIZE'],
            class_weight=class_weights,
            callbacks=callbacks,
            verbose=1
        )

        return self.history

    def evaluate(self, X_test, y_test):
        """
        Evaluate model dan buat confusion matrix.
        """
        print("\n📈 Evaluating model...")

        # Predictions
        y_pred_proba = self.model.predict(X_test, verbose=0)
        y_pred = np.argmax(y_pred_proba, axis=1)

        # Metrics
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, average='weighted')
        recall = recall_score(y_test, y_pred, average='weighted')
        f1 = f1_score(y_test, y_pred, average='weighted')

        print(f"\n✓ HASIL EVALUASI:")
        print(f"  • Accuracy:  {accuracy:.4f} ({accuracy*100:.2f}%)")
        print(f"  • Precision: {precision:.4f}")
        print(f"  • Recall:    {recall:.4f}")
        print(f"  • F1-Score:  {f1:.4f}")

        # Classification Report
        class_names = self.label_encoder.classes_
        print(f"\n📋 Classification Report:")
        print(classification_report(y_test, y_pred, target_names=class_names))

        # Confusion Matrix
        cm = confusion_matrix(y_test, y_pred)

        return {
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1_score': f1,
            'confusion_matrix': cm,
            'y_true': y_test,
            'y_pred': y_pred,
            'class_names': class_names
        }

    def plot_confusion_matrix(self, cm, class_names, title='Confusion Matrix (After Balancing)'):
        """
        Plot confusion matrix heatmap.
        """
        print("\n📊 Plotting Confusion Matrix...")

        plt.figure(figsize=(10, 8))

        # Normalize confusion matrix
        cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

        # Create annotation with counts and percentages
        annotations = np.array([[f'{val}\n({pct:.1%})'
                                for val, pct in zip(row, row_norm)]
                               for row, row_norm in zip(cm, cm_normalized)])

        sns.heatmap(cm, annot=annotations, fmt='', cmap='Blues',
                   xticklabels=class_names, yticklabels=class_names,
                   cbar_kws={'label': 'Count'})

        plt.title(title, fontsize=14, fontweight='bold')
        plt.ylabel('Actual', fontsize=12)
        plt.xlabel('Predicted', fontsize=12)

        plt.tight_layout()
        save_path = os.path.join(self.viz_dir, 'confusion_matrix_balanced.png')
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        plt.show()

        print(f"  ✓ Saved to: {save_path}")

    def plot_training_history(self):
        """
        Plot training history (loss dan accuracy).
        """
        if self.history is None:
            return

        print("\n📊 Plotting Training History...")

        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        # Loss
        ax1 = axes[0]
        ax1.plot(self.history.history['loss'], label='Training Loss', color='blue')
        ax1.plot(self.history.history['val_loss'], label='Validation Loss', color='red')
        ax1.set_title('Training & Validation Loss', fontsize=12, fontweight='bold')
        ax1.set_xlabel('Epoch')
        ax1.set_ylabel('Loss')
        ax1.legend()
        ax1.grid(True, alpha=0.3)

        # Accuracy
        ax2 = axes[1]
        ax2.plot(self.history.history['accuracy'], label='Training Accuracy', color='blue')
        ax2.plot(self.history.history['val_accuracy'], label='Validation Accuracy', color='red')
        ax2.set_title('Training & Validation Accuracy', fontsize=12, fontweight='bold')
        ax2.set_xlabel('Epoch')
        ax2.set_ylabel('Accuracy')
        ax2.legend()
        ax2.grid(True, alpha=0.3)

        plt.suptitle('LSTM Training History (Balanced Data)', fontsize=14, fontweight='bold')
        plt.tight_layout()

        save_path = os.path.join(self.viz_dir, 'lstm_training_history_balanced.png')
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        plt.show()

        print(f"  ✓ Saved to: {save_path}")

    def save_model(self):
        """
        Save model dan scaler.
        """
        print("\n💾 Saving model...")

        # Save model
        model_path = os.path.join(self.model_dir, 'lstm_balanced.keras')
        self.model.save(model_path)
        print(f"  ✓ Model saved: {model_path}")

        # Save scaler
        scaler_path = os.path.join(self.model_dir, 'lstm_scaler_balanced.pkl')
        with open(scaler_path, 'wb') as f:
            pickle.dump(self.scaler, f)
        print(f"  ✓ Scaler saved: {scaler_path}")

        # Save label encoder
        encoder_path = os.path.join(self.model_dir, 'label_encoder_balanced.pkl')
        with open(encoder_path, 'wb') as f:
            pickle.dump(self.label_encoder, f)
        print(f"  ✓ Label encoder saved: {encoder_path}")


# Inisialisasi classifier
lstm_classifier = ImprovedLSTMClassifier(output_dir=OUTPUT_DIR)
print("✓ LSTM Classifier initialized")

# =============================================================================
# TRAINING DENGAN DATA BALANCED
# =============================================================================

print("="*60)
print("TRAINING LSTM DENGAN DATA BALANCED")
print("="*60)

# Prepare features
X, y, feature_names = lstm_classifier.prepare_features(df_balanced, target_column='sentiment_category')

print(f"\n✓ Feature shape: {X.shape}")
print(f"✓ Target shape: {y.shape}")
print(f"✓ Classes: {lstm_classifier.label_encoder.classes_}")

# Split data
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print(f"\n📊 Data Split:")
print(f"  • Training:   {len(X_train):,} samples")
print(f"  • Validation: {len(X_val):,} samples")
print(f"  • Test:       {len(X_test):,} samples")

# Cek distribusi di training set
train_dist = pd.Series(y_train).value_counts()
print(f"\n📊 Distribusi di Training Set:")
for cls_idx, cnt in train_dist.items():
    cls_name = lstm_classifier.label_encoder.classes_[cls_idx]
    print(f"  • {cls_name}: {cnt:,}")

# Training
history = lstm_classifier.train(X_train, y_train, X_val, y_val)

print("\n✓ Training complete!")

# =============================================================================
# EVALUASI MODEL DAN CONFUSION MATRIX
# =============================================================================

print("="*60)
print("EVALUASI MODEL LSTM - DATA BALANCED")
print("="*60)

# Evaluate on test set
eval_results = lstm_classifier.evaluate(X_test, y_test)

# Plot confusion matrix
lstm_classifier.plot_confusion_matrix(
    eval_results['confusion_matrix'],
    eval_results['class_names'],
    title='Confusion Matrix - LSTM dengan Data Balanced'
)

# Plot training history
lstm_classifier.plot_training_history()

# Save model
lstm_classifier.save_model()

# =============================================================================
# ANALISIS CONFUSION MATRIX
# =============================================================================

print("\n" + "="*60)
print("ANALISIS CONFUSION MATRIX")
print("="*60)

cm = eval_results['confusion_matrix']
class_names = eval_results['class_names']

print(f"\n📊 Confusion Matrix:")
print(f"{'':>12} | " + " | ".join([f"{cn:>10}" for cn in class_names]) + " |")
print("-" * (15 + 13 * len(class_names)))

for i, row in enumerate(cm):
    print(f"{class_names[i]:>12} | " + " | ".join([f"{val:>10}" for val in row]) + " |")

# Per-class metrics
print(f"\n📊 Per-Class Metrics:")
for i, cls_name in enumerate(class_names):
    tp = cm[i, i]  # True Positive
    fp = cm[:, i].sum() - tp  # False Positive
    fn = cm[i, :].sum() - tp  # False Negative
    tn = cm.sum() - tp - fp - fn  # True Negative

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

    print(f"\n  {cls_name}:")
    print(f"    • Precision: {precision:.4f}")
    print(f"    • Recall:    {recall:.4f}")
    print(f"    • F1-Score:  {f1:.4f}")
    print(f"    • Support:   {cm[i, :].sum()}")

# Cek apakah semua kelas diprediksi
print(f"\n✅ VALIDASI PREDIKSI:")
for i, cls_name in enumerate(class_names):
    predicted_count = cm[:, i].sum()
    if predicted_count > 0:
        print(f"  ✓ Kelas '{cls_name}' diprediksi {predicted_count} kali")
    else:
        print(f"  ⚠️ Kelas '{cls_name}' TIDAK diprediksi sama sekali!")

# =============================================================================
# SUMMARY DAN REKOMENDASI
# =============================================================================

print("="*70)
print("SUMMARY: PERBAIKAN MODEL DENGAN HYBRID SAMPLING")
print("="*70)

# Save summary report
summary = {
    'timestamp': datetime.now().isoformat(),
    'original_data_count': len(df),
    'balanced_data_count': len(df_balanced),
    'distribution_before': df['sentiment_category'].value_counts().to_dict(),
    'distribution_after': df_balanced['sentiment_category'].value_counts().to_dict(),
    'model_metrics': {
        'accuracy': float(eval_results['accuracy']),
        'precision': float(eval_results['precision']),
        'recall': float(eval_results['recall']),
        'f1_score': float(eval_results['f1_score'])
    },
    'confusion_matrix': eval_results['confusion_matrix'].tolist(),
    'class_names': eval_results['class_names'].tolist(),
    'sampling_method': 'hybrid_sampling',
    'improvements': [
        'Back Translation capability (deep-translator)',
        'Hybrid Sampling (under + over sampling)',
        'Class weights in training',
        'Improved visualization'
    ]
}

summary_path = f'{OUTPUT_DIR}/evaluations/balancing_improvement_summary.json'
with open(summary_path, 'w', encoding='utf-8') as f:
    json.dump(summary, f, indent=2, ensure_ascii=False)

print(f"\n✅ Summary report saved to: {summary_path}")

print("\n" + "="*70)
print("✅ PIPELINE SELESAI!")
print("="*70)
print(f"""
📁 Output Files:
   • {OUTPUT_DIR}/visualizations/distribusi_sebelum_balancing.png
   • {OUTPUT_DIR}/visualizations/perbandingan_distribusi_balancing.png
   • {OUTPUT_DIR}/visualizations/confusion_matrix_balanced.png
   • {OUTPUT_DIR}/visualizations/lstm_training_history_balanced.png
   • {OUTPUT_DIR}/models/lstm_balanced.keras
   • {OUTPUT_DIR}/models/lstm_scaler_balanced.pkl
   • {OUTPUT_DIR}/evaluations/balancing_improvement_summary.json
""")

# =============================================================================
# VISUALISASI DISTRIBUSI GLOBAL MENTAL HEALTH CATEGORY
# =============================================================================

print("="*70)
print("VISUALISASI DISTRIBUSI GLOBAL MENTAL HEALTH CATEGORY")
print("="*70)

# Cek apakah kolom mh_category ada
if 'mh_category' not in df_balanced.columns:
    print("⚠️ Kolom 'mh_category' tidak ditemukan. Menggunakan data original.")
    df_analysis = df.copy()
else:
    df_analysis = df_balanced.copy()

# =============================================================================
# 1. DISTRIBUSI MENTAL HEALTH CATEGORY
# =============================================================================

print("\n📊 1. DISTRIBUSI MENTAL HEALTH CATEGORY")
mh_dist = df_analysis['mh_category'].value_counts()
print(mh_dist)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Bar chart
ax1 = axes[0]
colors_mh = plt.cm.Set3(np.linspace(0, 1, len(mh_dist)))
bars = ax1.bar(range(len(mh_dist)), mh_dist.values, color=colors_mh, edgecolor='black')
ax1.set_xticks(range(len(mh_dist)))
ax1.set_xticklabels(mh_dist.index, rotation=45, ha='right')
ax1.set_title('Distribusi Mental Health Category', fontsize=14, fontweight='bold')
ax1.set_xlabel('Mental Health Category', fontsize=12)
ax1.set_ylabel('Jumlah Data', fontsize=12)

# Tambahkan label nilai
for i, (cat, val) in enumerate(mh_dist.items()):
    ax1.text(i, val + 10, f'{val:,}', ha='center', fontsize=9, fontweight='bold')

# Pie chart
ax2 = axes[1]
ax2.pie(mh_dist.values, labels=mh_dist.index, autopct='%1.1f%%',
        colors=colors_mh, startangle=90)
ax2.set_title('Proporsi Mental Health Category', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/visualizations/mh_category_distribution.png', dpi=150, bbox_inches='tight')
plt.show()

# =============================================================================
# 2. CROSS-TABULATION: MENTAL HEALTH vs SENTIMENT
# =============================================================================

print("\n📊 2. CROSS-TABULATION: MENTAL HEALTH vs SENTIMENT")

# Buat cross-tabulation
cross_tab = pd.crosstab(df_analysis['mh_category'], df_analysis['sentiment_category'],
                        margins=True, margins_name='Total')
print(cross_tab)

# Heatmap cross-tabulation (tanpa margin Total)
cross_tab_no_margin = pd.crosstab(df_analysis['mh_category'], df_analysis['sentiment_category'])

plt.figure(figsize=(12, 10))
sns.heatmap(cross_tab_no_margin, annot=True, fmt='d', cmap='YlGnBu',
            linewidths=0.5, cbar_kws={'label': 'Count'})
plt.title('Heatmap: Mental Health Category vs Sentiment\n(Count per Cell)',
          fontsize=14, fontweight='bold')
plt.xlabel('Sentiment Category', fontsize=12)
plt.ylabel('Mental Health Category', fontsize=12)
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/visualizations/mh_sentiment_crosstab_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

# =============================================================================
# 3. NORMALIZED HEATMAP (PERCENTAGE PER MH CATEGORY)
# =============================================================================

print("\n📊 3. NORMALIZED HEATMAP (% per Mental Health Category)")

# Normalize per row (per MH category)
cross_tab_pct = cross_tab_no_margin.div(cross_tab_no_margin.sum(axis=1), axis=0) * 100

plt.figure(figsize=(12, 10))

# Custom annotations dengan percentage
annot_labels = cross_tab_pct.round(1).astype(str) + '%'

sns.heatmap(cross_tab_pct, annot=annot_labels, fmt='', cmap='RdYlGn',
            linewidths=0.5, cbar_kws={'label': 'Percentage (%)'},
            vmin=0, vmax=100)
plt.title('Heatmap: Sentiment Distribution per Mental Health Category\n(Normalized %)',
          fontsize=14, fontweight='bold')
plt.xlabel('Sentiment Category', fontsize=12)
plt.ylabel('Mental Health Category', fontsize=12)
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/visualizations/mh_sentiment_normalized_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

print("✓ Visualisasi tersimpan")

# =============================================================================
# 4. STACKED BAR CHART - SENTIMENT PER MH CATEGORY
# =============================================================================

print("\n📊 4. STACKED BAR CHART - SENTIMENT PER MENTAL HEALTH CATEGORY")

# Prepare data
sentiment_colors = {'Positif': '#2ecc71', 'Negatif': '#e74c3c', 'Netral': '#3498db'}

fig, ax = plt.subplots(figsize=(14, 8))

# Sort by total count
mh_order = df_analysis['mh_category'].value_counts().index.tolist()

# Create stacked bar
bottom = np.zeros(len(mh_order))
x = np.arange(len(mh_order))

for sentiment in ['Positif', 'Negatif', 'Netral']:
    counts = []
    for mh in mh_order:
        count = len(df_analysis[(df_analysis['mh_category'] == mh) &
                                (df_analysis['sentiment_category'] == sentiment)])
        counts.append(count)

    ax.bar(x, counts, bottom=bottom, label=sentiment,
           color=sentiment_colors[sentiment], edgecolor='white', linewidth=0.5)
    bottom += np.array(counts)

ax.set_xticks(x)
ax.set_xticklabels(mh_order, rotation=45, ha='right')
ax.set_xlabel('Mental Health Category', fontsize=12)
ax.set_ylabel('Jumlah Data', fontsize=12)
ax.set_title('Stacked Bar: Sentiment per Mental Health Category', fontsize=14, fontweight='bold')
ax.legend(title='Sentiment', loc='upper right')

# Add total labels on top
for i, total in enumerate(bottom):
    ax.text(i, total + 10, f'{int(total):,}', ha='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/visualizations/mh_sentiment_stacked_bar.png', dpi=150, bbox_inches='tight')
plt.show()

# =============================================================================
# 5. RADAR CHART - SENTIMENT PROFILE PER TOP MH CATEGORIES
# =============================================================================

print("\n📊 5. RADAR CHART - SENTIMENT PROFILE PER TOP MH CATEGORIES")

from math import pi

# Ambil top 6 kategori mental health
top_mh = mh_dist.head(6).index.tolist()

# Prepare data untuk radar chart
categories = ['Positif', 'Negatif', 'Netral']
N = len(categories)

# Calculate angles
angles = [n / float(N) * 2 * pi for n in range(N)]
angles += angles[:1]  # complete the loop

fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(polar=True))

colors_radar = plt.cm.Set2(np.linspace(0, 1, len(top_mh)))

for idx, mh in enumerate(top_mh):
    mh_data = df_analysis[df_analysis['mh_category'] == mh]
    total = len(mh_data)

    values = []
    for sent in categories:
        count = len(mh_data[mh_data['sentiment_category'] == sent])
        pct = (count / total * 100) if total > 0 else 0
        values.append(pct)

    values += values[:1]  # complete the loop

    ax.plot(angles, values, 'o-', linewidth=2, label=mh, color=colors_radar[idx])
    ax.fill(angles, values, alpha=0.1, color=colors_radar[idx])

ax.set_xticks(angles[:-1])
ax.set_xticklabels(categories, fontsize=12)
ax.set_title('Radar Chart: Sentiment Profile per Mental Health Category\n(Top 6 Categories)',
             fontsize=14, fontweight='bold', y=1.1)
ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.0))

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/visualizations/mh_sentiment_radar_chart.png', dpi=150, bbox_inches='tight')
plt.show()

print("✓ Radar chart tersimpan")

# =============================================================================
# 6. BALANCED MENTAL HEALTH CATEGORY - APPLY HYBRID SAMPLING
# =============================================================================

print("\n" + "="*70)
print("6. BALANCED MENTAL HEALTH CATEGORY")
print("="*70)

# Cek distribusi mh_category sebelum balancing
print("\n📊 Distribusi MH Category SEBELUM Balancing:")
mh_dist_before = df_analysis['mh_category'].value_counts()
print(mh_dist_before)

# Apply hybrid sampling untuk mh_category
df_mh_balanced = sampler.balance_dataset(
    df_analysis.copy(),
    target_column='mh_category',
    target_count=None,  # Otomatis ke median
    use_back_translation=False,
    text_column='processed_text'
)

# Visualisasi perbandingan
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# SEBELUM
ax1 = axes[0]
mh_before = df_analysis['mh_category'].value_counts()
colors_before = plt.cm.Reds(np.linspace(0.3, 0.9, len(mh_before)))
bars1 = ax1.barh(range(len(mh_before)), mh_before.values, color=colors_before, edgecolor='black')
ax1.set_yticks(range(len(mh_before)))
ax1.set_yticklabels(mh_before.index)
ax1.set_xlabel('Jumlah Data', fontsize=12)
ax1.set_title('SEBELUM Balancing\n(Imbalanced)', fontsize=14, fontweight='bold', color='red')
ax1.axvline(x=mh_before.median(), color='green', linestyle='--', linewidth=2, label=f'Median: {int(mh_before.median())}')
ax1.legend()

# Tambahkan nilai
for i, val in enumerate(mh_before.values):
    ax1.text(val + 5, i, f'{val:,}', va='center', fontsize=9)

# SESUDAH
ax2 = axes[1]
mh_after = df_mh_balanced['mh_category'].value_counts()
colors_after = plt.cm.Greens(np.linspace(0.3, 0.9, len(mh_after)))
bars2 = ax2.barh(range(len(mh_after)), mh_after.values, color=colors_after, edgecolor='black')
ax2.set_yticks(range(len(mh_after)))
ax2.set_yticklabels(mh_after.index)
ax2.set_xlabel('Jumlah Data', fontsize=12)
ax2.set_title('SESUDAH Balancing\n(Balanced)', fontsize=14, fontweight='bold', color='green')
target = mh_after.values[0] if len(mh_after) > 0 else 0
ax2.axvline(x=target, color='green', linestyle='--', linewidth=2, label=f'Target: {target:,}')
ax2.legend()

# Tambahkan nilai
for i, val in enumerate(mh_after.values):
    ax2.text(val + 5, i, f'{val:,}', va='center', fontsize=9)

plt.suptitle('Perbandingan Distribusi Mental Health Category\nSebelum vs Sesudah Hybrid Sampling',
             fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/visualizations/mh_category_balancing_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

# Report
print("\n📊 PERBANDINGAN IMBALANCE RATIO (MH Category):")
ratio_mh_before = mh_before.max() / mh_before.min()
ratio_mh_after = mh_after.max() / mh_after.min()
print(f"  • SEBELUM: {ratio_mh_before:.2f}x")
print(f"  • SESUDAH: {ratio_mh_after:.2f}x")
print(f"  • Improvement: {((ratio_mh_before - ratio_mh_after) / ratio_mh_before * 100):.1f}% lebih seimbang")

# =============================================================================
# 7. COMPREHENSIVE CONFUSION MATRIX - PER MH CATEGORY
# =============================================================================

print("\n" + "="*70)
print("7. CONFUSION MATRIX ANALYSIS PER MENTAL HEALTH CATEGORY")
print("="*70)

# Train model dengan data balanced per MH category
print("\n🔄 Re-training model dengan balanced MH Category data...")

# Prepare features untuk df_mh_balanced
X_mh, y_mh, _ = lstm_classifier.prepare_features(df_mh_balanced, target_column='sentiment_category')

# Split data
X_train_mh, X_temp_mh, y_train_mh, y_temp_mh = train_test_split(
    X_mh, y_mh, test_size=0.3, random_state=42, stratify=y_mh
)
X_val_mh, X_test_mh, y_val_mh, y_test_mh = train_test_split(
    X_temp_mh, y_temp_mh, test_size=0.5, random_state=42, stratify=y_temp_mh
)

print(f"✓ Data split: Train={len(X_train_mh)}, Val={len(X_val_mh)}, Test={len(X_test_mh)}")

# Train
lstm_classifier.train(X_train_mh, y_train_mh, X_val_mh, y_val_mh)

# Evaluate
eval_mh = lstm_classifier.evaluate(X_test_mh, y_test_mh)

# Plot enhanced confusion matrix
lstm_classifier.plot_confusion_matrix(
    eval_mh['confusion_matrix'],
    eval_mh['class_names'],
    title='Confusion Matrix - Balanced MH Category + Sentiment'
)

print("\n✓ Model retrained dengan balanced MH Category data")

# =============================================================================
# 8. GLOBAL HEATMAP - PREDICTION DISTRIBUTION PER MH CATEGORY
# =============================================================================

print("\n" + "="*70)
print("8. GLOBAL HEATMAP - PREDICTION DISTRIBUTION PER MH CATEGORY")
print("="*70)

# Untuk setiap MH category, hitung distribusi prediksi sentiment
print("\n🔄 Menghitung distribusi prediksi per MH Category...")

# Prepare data
df_mh_balanced['mh_category_encoded'] = df_mh_balanced['mh_category'].astype('category').cat.codes
mh_categories = df_mh_balanced['mh_category'].unique()
sentiment_classes = lstm_classifier.label_encoder.classes_

# Build matrix: rows = MH categories, cols = predicted sentiment
prediction_matrix = np.zeros((len(mh_categories), len(sentiment_classes)))

for i, mh in enumerate(mh_categories):
    # Filter data untuk MH category ini
    mask = df_mh_balanced['mh_category'] == mh
    X_mh_subset, y_mh_subset, _ = lstm_classifier.prepare_features(
        df_mh_balanced[mask].copy(),
        target_column='sentiment_category'
    )

    if len(X_mh_subset) > 0:
        # Predict
        y_pred_proba = lstm_classifier.model.predict(X_mh_subset, verbose=0)
        y_pred = np.argmax(y_pred_proba, axis=1)

        # Count predictions per class
        for j in range(len(sentiment_classes)):
            prediction_matrix[i, j] = np.sum(y_pred == j)

# Normalize to percentage
prediction_matrix_pct = prediction_matrix / prediction_matrix.sum(axis=1, keepdims=True) * 100

# Create DataFrame for heatmap
df_heatmap = pd.DataFrame(prediction_matrix_pct,
                          index=mh_categories,
                          columns=sentiment_classes)

# Sort by total positif (descending)
df_heatmap = df_heatmap.sort_values('Positif', ascending=True)

# Plot
plt.figure(figsize=(14, 12))

# Custom annotations
annot_labels = df_heatmap.round(1).astype(str) + '%'

sns.heatmap(df_heatmap, annot=annot_labels, fmt='', cmap='RdYlGn',
            linewidths=0.5, cbar_kws={'label': 'Percentage (%)'},
            vmin=0, vmax=100)

plt.title('Global Heatmap: Predicted Sentiment Distribution per Mental Health Category\n(After Balanced Training)',
          fontsize=14, fontweight='bold')
plt.xlabel('Predicted Sentiment', fontsize=12)
plt.ylabel('Mental Health Category', fontsize=12)
plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/visualizations/global_mh_prediction_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

print("✓ Global heatmap tersimpan")

# =============================================================================
# 9. SUMMARY STATISTICS
# =============================================================================

print("\n" + "="*70)
print("SUMMARY: DISTRIBUSI PREDIKSI PER MENTAL HEALTH CATEGORY")
print("="*70)

for mh in df_heatmap.index:
    row = df_heatmap.loc[mh]
    dominant = row.idxmax()
    print(f"\n📌 {mh}:")
    for sent in sentiment_classes:
        indicator = "★" if sent == dominant else "  "
        print(f"   {indicator} {sent}: {row[sent]:.1f}%")

# =============================================================================
# 10. FINAL COMPREHENSIVE VISUALIZATION - ALL IN ONE
# =============================================================================

print("\n" + "="*70)
print("10. COMPREHENSIVE DASHBOARD - MENTAL HEALTH ANALYSIS")
print("="*70)

# Create a comprehensive figure with multiple subplots
fig = plt.figure(figsize=(20, 16))

# Define grid
gs = fig.add_gridspec(3, 3, hspace=0.3, wspace=0.3)

# --- Plot 1: MH Category Distribution (Top Left) ---
ax1 = fig.add_subplot(gs[0, 0])
mh_counts = df_mh_balanced['mh_category'].value_counts()
colors1 = plt.cm.Set3(np.linspace(0, 1, len(mh_counts)))
ax1.barh(range(len(mh_counts)), mh_counts.values, color=colors1, edgecolor='black')
ax1.set_yticks(range(len(mh_counts)))
ax1.set_yticklabels(mh_counts.index, fontsize=9)
ax1.set_xlabel('Count')
ax1.set_title('A. MH Category Distribution\n(Balanced)', fontweight='bold')
for i, v in enumerate(mh_counts.values):
    ax1.text(v + 5, i, f'{v}', va='center', fontsize=8)

# --- Plot 2: Sentiment Distribution (Top Middle) ---
ax2 = fig.add_subplot(gs[0, 1])
sent_counts = df_mh_balanced['sentiment_category'].value_counts()
colors2 = ['#2ecc71', '#e74c3c', '#3498db']
ax2.pie(sent_counts.values, labels=sent_counts.index, autopct='%1.1f%%',
        colors=colors2, startangle=90)
ax2.set_title('B. Sentiment Distribution\n(Balanced)', fontweight='bold')

# --- Plot 3: Confusion Matrix (Top Right) ---
ax3 = fig.add_subplot(gs[0, 2])
cm = eval_mh['confusion_matrix']
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis] * 100
sns.heatmap(cm_normalized, annot=True, fmt='.1f', cmap='Blues',
            xticklabels=eval_mh['class_names'],
            yticklabels=eval_mh['class_names'], ax=ax3)
ax3.set_title('C. Confusion Matrix (%)\n(Sentiment Classification)', fontweight='bold')
ax3.set_xlabel('Predicted')
ax3.set_ylabel('Actual')

# --- Plot 4: Cross-tab Heatmap (Middle Left + Center) ---
ax4 = fig.add_subplot(gs[1, :2])
cross_tab_pct = pd.crosstab(df_mh_balanced['mh_category'],
                            df_mh_balanced['sentiment_category'], normalize='index') * 100
sns.heatmap(cross_tab_pct, annot=True, fmt='.1f', cmap='RdYlGn',
            cbar_kws={'label': '%'}, ax=ax4, vmin=0, vmax=100)
ax4.set_title('D. Sentiment Distribution per MH Category (%)', fontweight='bold')
ax4.set_xlabel('Sentiment Category')
ax4.set_ylabel('Mental Health Category')

# --- Plot 5: Model Performance Metrics (Middle Right) ---
ax5 = fig.add_subplot(gs[1, 2])
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
values = [eval_mh['accuracy'], eval_mh['precision'], eval_mh['recall'], eval_mh['f1_score']]
colors5 = plt.cm.RdYlGn(np.array(values))
bars = ax5.barh(metrics, values, color=colors5, edgecolor='black')
ax5.set_xlim(0, 1.1)
ax5.set_title('E. Model Performance Metrics', fontweight='bold')
ax5.set_xlabel('Score')
for i, v in enumerate(values):
    ax5.text(v + 0.02, i, f'{v:.3f}', va='center', fontsize=10, fontweight='bold')

# --- Plot 6: Stacked bar per top 5 MH categories (Bottom) ---
ax6 = fig.add_subplot(gs[2, :])
top_5_mh = mh_counts.head(5).index.tolist()
sentiment_colors = {'Positif': '#2ecc71', 'Negatif': '#e74c3c', 'Netral': '#3498db'}
x = np.arange(len(top_5_mh))
width = 0.25

for idx, sentiment in enumerate(['Positif', 'Negatif', 'Netral']):
    counts = []
    for mh in top_5_mh:
        count = len(df_mh_balanced[(df_mh_balanced['mh_category'] == mh) &
                                   (df_mh_balanced['sentiment_category'] == sentiment)])
        counts.append(count)
    ax6.bar(x + idx*width - width, counts, width, label=sentiment,
            color=sentiment_colors[sentiment], edgecolor='black')

ax6.set_xticks(x)
ax6.set_xticklabels(top_5_mh, rotation=15, ha='right')
ax6.set_xlabel('Mental Health Category')
ax6.set_ylabel('Count')
ax6.set_title('F. Sentiment Breakdown for Top 5 Mental Health Categories', fontweight='bold')
ax6.legend(title='Sentiment')

plt.suptitle('COMPREHENSIVE MENTAL HEALTH ANALYSIS DASHBOARD\n(After Hybrid Sampling Balancing)',
             fontsize=18, fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/visualizations/comprehensive_mh_dashboard.png', dpi=200, bbox_inches='tight')
plt.show()

print("\n✅ Comprehensive dashboard tersimpan!")
print(f"\n📁 Semua visualisasi tersimpan di: {OUTPUT_DIR}/visualizations/")
print("""
📊 FILES GENERATED:
   1. mh_category_distribution.png - Distribusi MH Category
   2. mh_sentiment_crosstab_heatmap.png - Cross-tab Heatmap (Count)
   3. mh_sentiment_normalized_heatmap.png - Cross-tab Heatmap (%)
   4. mh_sentiment_stacked_bar.png - Stacked Bar Chart
   5. mh_sentiment_radar_chart.png - Radar Chart (Top 6)
   6. mh_category_balancing_comparison.png - Before vs After Balancing
   7. global_mh_prediction_heatmap.png - Prediction Distribution
   8. comprehensive_mh_dashboard.png - All-in-One Dashboard
""")